@startuml

class Iso8601_date {
  + year() : Integer [1]
  + month() : Integer [1]
  + day() : Integer [1]
  + timezone() : Iso8601_timezone [1]
  + month_unknown() : Boolean [1]
  + day_unknown() : Boolean [1]
  + is_partial() : Boolean [1]
  + is_extended() : Boolean [1]
  + as_string() : String [1]
  + add( a_diff : Iso8601_duration [1] ) : Iso8601_date [1]
  + subtract( a_diff : Iso8601_duration [1] ) : Iso8601_date [1]
  + diff( a_date : Iso8601_date [1] ) : Iso8601_duration [1]
  + add_nominal( a_diff : Iso8601_duration [1] ) : Iso8601_date [1]
  + subtract_nominal( a_diff : Iso8601_duration [1] ) : Iso8601_date [1]
}

abstract class Iso8601_type  #whitesmoke;line:gray;line.dotted;text:gray {
  + value : String [1]
  + {abstract} is_partial() : Boolean [1]
  + {abstract} is_extended() : Boolean [1]
}

abstract class Ordered  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} infix <( other : Ordered [1] ) : Boolean [1]
}

Ordered <|-- Iso8601_type

Iso8601_type <|-- Iso8601_date


@enduml