@startuml
' PlantUML diagram for org.openehr.base.foundation_types.terminology.Terminology_code
title Terminology_code Class

class Terminology_code {
  + terminology_id : String [1..1]
  + terminology_version : String [0..1]
  + code_string : String [1..1]
  + uri : Uri [0..1]
}


@enduml