@startuml

class TERMINOLOGY {
  + name : String [1]
  + language : String [1]
  + code_sets : List<CODE_SET> [*]
  + vocabularies : List<TERMINOLOGY_GROUP> [*]
  + version : String [0..1]
  + date : Iso8601_date [0..1]
}


@enduml