@startuml
' PlantUML diagram for org.openehr.base.foundation_types.time.Time_Definitions
title Time_Definitions Class

class Time_Definitions {
  + valid_year(Integer y) : Boolean [0..1]
  + valid_month(Integer m) : Boolean [0..1]
  + valid_day(Integer y, Integer m, Integer d) : Boolean [0..1]
  + valid_hour(Integer h, Integer m, Integer s) : Boolean [0..1]
  + valid_minute(Integer m) : Boolean [0..1]
  + valid_second(Integer s) : Boolean [0..1]
  + valid_fractional_second(Double fs) : Boolean [0..1]
}


@enduml