=== Integer64 Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Integer64*

h|*Description*
2+a|Type representing minimal interface of built-in Integer64 type.

h|*Inherit*
2+|`<<_ordered_numeric_class,Ordered_Numeric>>`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*add* ( +
other: `<<_integer_class,Integer>>[1]` +
): `<<_integer64_class,Integer64>>`
a|Large integer addition.

h|*1..1*
|*subtract* ( +
other: `<<_integer_class,Integer>>[1]` +
): `<<_integer64_class,Integer64>>`
a|Large integer subtraction.

h|*1..1*
|*multiply* ( +
other: `<<_integer_class,Integer>>[1]` +
): `<<_integer64_class,Integer64>>`
a|Large integer multiplication.

h|*1..1*
|*divide* ( +
other: `<<_integer_class,Integer>>[1]` +
): `<<_double_class,Double>>`
a|Large integer division.

h|*1..1*
|*exponent* ( +
other: `<<_double_class,Double>>[1]` +
): `<<_double_class,Double>>`
a|Large integer exponentiation.

h|*1..1*
|*modulo* ( +
mod: `<<_integer_class,Integer>>[1]` +
): `<<_integer64_class,Integer64>>`
a|Large integer modulus.

h|*1..1*
|*less_than* ( +
other: `<<_integer64_class,Integer64>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Returns True if current Integer is less than `_other_`.

h|*1..1*
|*negative* (): `<<_integer64_class,Integer64>>`
a|Generate negative of current Integer value.

h|*1..1*
|*is_equal* ( +
other: `<<_integer64_class,Integer64>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

h|*1..1*
|*equal* ( +
other: `<<_integer64_class,Integer64>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Reference equality for reference types, value equality for value types.
|===
