@startuml
' PlantUML diagram for org.openehr.base.bmm.core.BMM_INDEXED_CONTAINER_TYPE
title BMM_INDEXED_CONTAINER_TYPE Class

class BMM_INDEXED_CONTAINER_TYPE {
  + index_type : BMM_SIMPLE_TYPE [1..1]
}

class BMM_CONTAINER_TYPE {
  + container_class : BMM_GENERIC_CLASS [1..1]
  + base_type : BMM_UNITARY_TYPE [1..1]
  + type_name() : String [0..1]
  + effective_base_class() : BMM_CLASS [0..1]
  + is_abstract() : Boolean [0..1]
  + entity_metatype() : String [0..1]
  + flattened_type_list() : List<String> [0..*]
  + subtypes() : List<String> [0..*]
  + has_subtypes() : Boolean [0..1]
}

abstract class BMM_TYPE {
  + {abstract} effective_base_class() : BMM_CLASS [0..1]
  + {abstract} type_name() : String [0..1]
  + {abstract} has_subtypes() : Boolean [0..1]
  + {abstract} subtypes() : List<String> [0..*]
  + {abstract} flattened_type_list() : List<String> [0..*]
  + type_signature() : String [0..1]
  + is_primitive() : Boolean [0..1]
  + entity_metatype() : String [0..1]
}

abstract class BMM_ENTITY {
  + {abstract} entity_category() : String [0..1]
  + {abstract} entity_metatype() : String [0..1]
  + {abstract} is_abstract() : Boolean [0..1]
  + {abstract} is_primitive() : Boolean [0..1]
}

class BMM_DEFINITIONS {
}

BMM_DEFINITIONS <|-- BMM_ENTITY

BMM_ENTITY <|-- BMM_TYPE

BMM_TYPE <|-- BMM_CONTAINER_TYPE

BMM_CONTAINER_TYPE <|-- BMM_INDEXED_CONTAINER_TYPE


@enduml