@startuml
' PlantUML diagram for org.openehr.base.bmm.core.BMM_MODEL_ELEMENT
title BMM_MODEL_ELEMENT Class

abstract class BMM_MODEL_ELEMENT {
  + documentation : String [0..1]
}

class BMM_DEFINITIONS {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ELEMENT


@enduml