@startuml

class BMM_ENUMERATION_INTEGER {
}

class BMM_ENUMERATION <T>  #whitesmoke;line:gray;line.dotted;text:gray {
  + item_names : List<String> [*]
  + item_values : T [0..1]
  + entity_metatype() : String [1]
  + name_map() : Hash<String,String> [1]
}

class BMM_SIMPLE_CLASS  #whitesmoke;line:gray;line.dotted;text:gray {
  + type() : BMM_SIMPLE_TYPE [1]
  + entity_metatype() : String [1]
}

abstract class BMM_CLASS  #whitesmoke;line:gray;line.dotted;text:gray {
  + name : String [1]
  + ancestors : List<String> [*]
  + package : BMM_PACKAGE [1]
  + properties : Hash<String,BMM_PROPERTY> [0..1]
  + source_schema_id : String [1]
  + immediate_descendants : List<BMM_CLASS> [*]
  + is_override : Boolean [1]
  + all_ancestors() : List<String> [*]
  + all_descendants() : List<String> [*]
  + suppliers() : List<String> [*]
  + suppliers_non_primitive() : List<String> [*]
  + supplier_closure() : List<String> [*]
  + package_path() : String [1]
  + class_path() : String [1]
  + flat_properties() : List<Hash<String,BMM_PROPERTY<BMM_TYPE>>> [*]
  + is_primitive() : Boolean [1]
  + is_abstract() : Boolean [1]
  + {abstract} type() : BMM_DEFINED_TYPE [1]
}

abstract class BMM_ENTITY  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} entity_category() : String [1]
  + {abstract} entity_metatype() : String [1]
  + {abstract} is_abstract() : Boolean [1]
  + {abstract} is_primitive() : Boolean [1]
}

class BMM_DEFINITIONS  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_DEFINITIONS <|-- BMM_ENTITY

BMM_ENTITY <|-- BMM_CLASS

abstract class BMM_MODEL_ELEMENT  #whitesmoke;line:gray;line.dotted;text:gray {
  + documentation : String [0..1]
}

class BMM_DEFINITIONS  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ELEMENT

BMM_MODEL_ELEMENT <|-- BMM_CLASS

BMM_CLASS <|-- BMM_SIMPLE_CLASS

BMM_SIMPLE_CLASS <|-- BMM_ENUMERATION

BMM_ENUMERATION <|-- BMM_ENUMERATION_INTEGER


@enduml