@startuml
' PlantUML diagram for org.openehr.base.bmm.core.BMM_ENTITY
title BMM_ENTITY Class

abstract class BMM_ENTITY {
  + {abstract} entity_category() : String [0..1]
  + {abstract} entity_metatype() : String [0..1]
  + {abstract} is_abstract() : Boolean [0..1]
  + {abstract} is_primitive() : Boolean [0..1]
}

class BMM_DEFINITIONS {
}

BMM_DEFINITIONS <|-- BMM_ENTITY


@enduml