@startuml

class BMM_CONTAINER_PROPERTY {
  + type : BMM_CONTAINER_TYPE [1]
  + cardinality : Multiplicity_interval [0..1]
  + display_name() : String [1]
}

class BMM_PROPERTY <T>  #whitesmoke;line:gray;line.dotted;text:gray {
  + name : String [1]
  + is_mandatory : Boolean [0..1]
  + is_computed : Boolean [0..1]
  + type : T [1]
  + is_im_runtime : Boolean [0..1]
  + is_im_infrastructure : Boolean [0..1]
  + is_synthesised_generic : Boolean [0..1]
  + existence() : Multiplicity_interval [1]
  + display_name() : String [1]
}

abstract class BMM_MODEL_ELEMENT  #whitesmoke;line:gray;line.dotted;text:gray {
  + documentation : String [0..1]
}

class BMM_DEFINITIONS  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ELEMENT

BMM_MODEL_ELEMENT <|-- BMM_PROPERTY

BMM_PROPERTY <|-- BMM_CONTAINER_PROPERTY


@enduml