@startuml

abstract class BMM_UNITARY_TYPE {
}

abstract class BMM_TYPE  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} effective_base_class() : BMM_CLASS [1]
  + {abstract} type_name() : String [1]
  + {abstract} has_subtypes() : Boolean [1]
  + {abstract} subtypes() : List<String> [1..*]
  + {abstract} flattened_type_list() : List<String> [1..*]
  + type_signature() : String [1]
  + is_primitive() : Boolean [1]
  + entity_metatype() : String [1]
}

abstract class BMM_ENTITY  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} entity_category() : String [1]
  + {abstract} entity_metatype() : String [1]
  + {abstract} is_abstract() : Boolean [1]
  + {abstract} is_primitive() : Boolean [1]
}

class BMM_DEFINITIONS  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_DEFINITIONS <|-- BMM_ENTITY

BMM_ENTITY <|-- BMM_TYPE

BMM_TYPE <|-- BMM_UNITARY_TYPE


@enduml