@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types.Boolean
title Boolean Class

class Boolean {
  + infix and(Boolean other) : Boolean [0..1]
  + infix and_then(Boolean other) : Boolean [0..1]
  + infix or(Boolean other) : Boolean [0..1]
  + infix or_else(Boolean other) : Boolean [0..1]
  + infix xor(Boolean other) : Boolean [0..1]
  + infix implies(Boolean other) : Boolean [0..1]
}


@enduml