@startuml

class Integer64 {
}

abstract class Ordered_Numeric  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class Ordered  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} infix <( other : Ordered [1] ) : Boolean [1]
}

Ordered <|-- Ordered_Numeric

abstract class Numeric  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} infix *( other : Numeric [1] ) : Numeric [1]
  + {abstract} infix +( other : Numeric [1] ) : Numeric [1]
  + {abstract} infix -( other : Numeric [1] ) : Numeric [1]
}

Numeric <|-- Ordered_Numeric

Ordered_Numeric <|-- Integer64


@enduml