@startuml

abstract class Numeric {
  + {abstract} infix *( other : Numeric [1] ) : Numeric [1]
  + {abstract} infix +( other : Numeric [1] ) : Numeric [1]
  + {abstract} infix -( other : Numeric [1] ) : Numeric [1]
}


@enduml