@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types.Numeric
title Numeric Class

abstract class Numeric {
  + {abstract} infix *(Numeric other) : Numeric [0..1]
  + {abstract} infix +(Numeric other) : Numeric [0..1]
  + {abstract} infix -(Numeric other) : Numeric [0..1]
}


@enduml