@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types.String
title String Class

class String {
  + infix +(String other) : String [0..1]
  + is_empty() : Boolean [0..1]
  + is_integer() : Boolean [0..1]
  + as_integer() : Integer [0..1]
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- String


@enduml