@startuml
' PlantUML diagram for org.openehr.base.expression.types.TYPE_DEF_DATE
title TYPE_DEF_DATE Class

class TYPE_DEF_DATE {
  + type_name : String [1..1]
  + type_anchor : IDate [1..1]
}

abstract class EXPR_TYPE_DEF {
  + type_name : String [1..1]
  + type_anchor : Any [1..1]
}

EXPR_TYPE_DEF <|-- TYPE_DEF_DATE


@enduml