@startuml

abstract class Container <T> {
  + {abstract} has( v : T [1] ) : Boolean [1]
  + {abstract} count() : Integer [1]
  + {abstract} is_empty() : Boolean [1]
  + there_exists( test : Operation [1] ) : Boolean [1]
  + for_all( test : Operation [1] ) : Boolean [1]
  + matching( test : Operation [1] ) : List<T> [*]
  + select( test : Operation [1] ) : T [0..1]
}


@enduml