@startuml
' PlantUML diagram for org.openehr.lang.bmm.core.feature.BMM_WRITABLE_VARIABLE
title BMM_WRITABLE_VARIABLE Class

abstract class BMM_WRITABLE_VARIABLE {
}

abstract class BMM_VARIABLE {
  + scope : BMM_ROUTINE [1..1]
  + signature() :  [0..1]
}

abstract class BMM_INSTANTIABLE {
}

abstract class BMM_TYPED_FEATURE {
  + is_nullable : Boolean [0..1]
}

abstract class BMM_TYPED {
  + type : BMM_TYPE [1..1]
  + is_boolean() : Boolean [0..1]
}

BMM_TYPED <|-- BMM_TYPED_FEATURE

BMM_TYPED_FEATURE <|-- BMM_INSTANTIABLE

BMM_INSTANTIABLE <|-- BMM_VARIABLE

abstract class BMM_CLASS_ENTITY {
  + is_synthesised_generic : Boolean [0..1]
  + {abstract} signature() : BMM_SIGNATURE [0..1]
}

abstract class BMM_DECLARATION {
  + name : String [1..1]
  + documentation : Hash<String,Any> [0..1]
  + scope : BMM_DECLARATION [1..1]
  + extensions : Hash<String,Any> [0..1]
  + is_root_scope() : Boolean [0..1]
}

BMM_DECLARATION <|-- BMM_CLASS_ENTITY

BMM_CLASS_ENTITY <|-- BMM_VARIABLE

BMM_VARIABLE <|-- BMM_WRITABLE_VARIABLE


@enduml