@startuml

class EXPR_CONSTRAINT {
  + item : C_PRIMITIVE_OBJECT [1]
}

class EXPR_LEAF  #whitesmoke;line:gray;line.dotted;text:gray {
  + reference_type : String [1]
  + item : Any [1]
}

abstract class EXPR_ITEM  #whitesmoke;line:gray;line.dotted;text:gray {
  + type : String [1]
}

EXPR_ITEM <|-- EXPR_LEAF

EXPR_LEAF <|-- EXPR_CONSTRAINT


@enduml