@startuml
' PlantUML diagram for org.openehr.base.foundation_types.structures.Array
title Array Class

class Array <<T>> {
}

abstract class Container <<T>> {
  + {abstract} has(T v) : Boolean [0..1]
  + {abstract} count() : Integer [0..1]
  + {abstract} is_empty() : Boolean [0..1]
}

Container <|-- Array


@enduml