@startuml
' PlantUML diagram for org.openehr.am.aom14.archetype.assertion.EXPR_OPERATOR
title EXPR_OPERATOR Class

abstract class EXPR_OPERATOR {
  + precedence_overridden : Boolean [0..1]
  + operator : OPERATOR_KIND [1..1]
}

abstract class EXPR_ITEM {
  + type : String [1..1]
}

EXPR_ITEM <|-- EXPR_OPERATOR


@enduml