@startuml
' PlantUML diagram for org.openehr.rm.data_types.text.CODE_PHRASE
title CODE_PHRASE Class

class CODE_PHRASE {
  + terminology_id : TERMINOLOGY_ID [1..1]
  + code_string : String [1..1]
  + preferred_term : String [0..1]
}


@enduml