@startuml
' PlantUML diagram for org.openehr.base.base_types.identification.ACCESS_GROUP_REF
title ACCESS_GROUP_REF Class

class ACCESS_GROUP_REF {
}

class OBJECT_REF {
  + namespace : String [1..1]
  + type : String [1..1]
  + id : OBJECT_ID [1..1]
}

OBJECT_REF <|-- ACCESS_GROUP_REF


@enduml