@startuml
' PlantUML diagram for org.openehr.base.base_types.identification.VERSION_TREE_ID
title VERSION_TREE_ID Class

class VERSION_TREE_ID {
  + value : String [1..1]
  + trunk_version() : String [0..1]
  + is_branch() : Boolean [0..1]
  + branch_number() : String [0..1]
  + branch_version() : String [0..1]
}


@enduml