@startuml
' PlantUML diagram for org.openehr.am.p_aom2.constraint_model
title constraint_model Package

abstract class P_ARCHETYPE_CONSTRAINT {
}

abstract class P_C_OBJECT {
  + rm_type_name : String [1..1]
  + occurrences : String [0..1]
  + node_id : String [1..1]
  + is_deprecated : Boolean [0..1]
  + specialisation_depth() : Integer [0..1]
}

class P_C_ATTRIBUTE {
  + rm_attribute_name : String [1..1]
  + existence : String [0..1]
  + children : List<P_C_OBJECT> [0..*]
  + differential_path : String [0..1]
  + cardinality : String [0..1]
  + is_multiple : Boolean [1..1]
}

abstract class P_C_DEFINED_OBJECT {
  + is_frozen : Boolean [0..1]
  + default_value : Any [1..1]
}

class P_C_COMPLEX_OBJECT_PROXY {
  + target_path : String [1..1]
}

class P_ARCHETYPE_SLOT {
  + includes : List<> [0..*]
  + excludes : List<> [0..*]
  + is_closed : Boolean [1..1]
}

abstract class P_C_PRIMITIVE_OBJECT {
  + assumed_value : Any [0..1]
  + is_enumerated_type_constraint : Boolean [0..1]
  + constraint : Any [1..1]
}

class P_C_COMPLEX_OBJECT {
  + attributes : List<P_C_ATTRIBUTE> [0..*]
  + attribute_tuples : List<P_C_ATTRIBUTE_TUPLE> [0..*]
}

class P_C_ATTRIBUTE_TUPLE {
  + members : List<String> [0..*]
}

class P_C_ARCHETYPE_ROOT {
  + archetype_ref : String [1..1]
}

P_ARCHETYPE_CONSTRAINT <|-- P_C_OBJECT
P_ARCHETYPE_CONSTRAINT <|-- P_C_ATTRIBUTE
P_C_OBJECT <|-- P_C_DEFINED_OBJECT
P_C_OBJECT <|-- P_C_COMPLEX_OBJECT_PROXY
P_C_OBJECT <|-- P_ARCHETYPE_SLOT
P_C_DEFINED_OBJECT <|-- P_C_PRIMITIVE_OBJECT
P_C_DEFINED_OBJECT <|-- P_C_COMPLEX_OBJECT
P_C_COMPLEX_OBJECT <|-- P_C_ARCHETYPE_ROOT

@enduml