@startuml

abstract class ARCHETYPE {
  + parent_archetype_id : String [0..1]
  + archetype_id : ARCHETYPE_HRID [1]
  + is_differential : Boolean [1]
  + definition : C_COMPLEX_OBJECT [1]
  + terminology : ARCHETYPE_TERMINOLOGY [1]
  + rules : List<STATEMENT> [*]
  + rm_overlay : RM_OVERLAY [0..1]
  + concept_code() : String [1]
  + physical_paths() : List<String> [1..*]
  + logical_paths( lang : String [1] ) : List<String> [1..*]
  + specialisation_depth() : Integer [1]
  + is_specialised() : Boolean [1]
}

class AUTHORED_ARCHETYPE {
  + adl_version : String [0..1]
  + build_uid : UUID [1]
  + rm_release : String [1]
  + is_generated : Boolean [1]
  + other_meta_data : Hash<String,String> [1]
}

class TEMPLATE {
  + overlays : List<TEMPLATE_OVERLAY> [*]
}

class OPERATIONAL_TEMPLATE {
  + component_terminologies : Hash<String,ARCHETYPE_TERMINOLOGY> [0..1]
  + terminology_extracts : Hash<String,ARCHETYPE_TERMINOLOGY> [0..1]
  + component_terminology( an_id : String [1] ) : ARCHETYPE_TERMINOLOGY [1]
}

class TEMPLATE_OVERLAY {
}

class ARCHETYPE_HRID {
  + namespace : String [0..1]
  + rm_publisher : String [1]
  + rm_package : String [1]
  + rm_class : String [1]
  + concept_id : String [1]
  + release_version : String [1]
  + version_status : VERSION_STATUS [1]
  + build_count : String [1]
  + semantic_id() : String [1]
  + physical_id() : String [1]
  + version_id() : String [1]
  + major_version() : String [1]
  + minor_version() : String [1]
  + patch_version() : String [1]
}

ARCHETYPE <|-- AUTHORED_ARCHETYPE
AUTHORED_RESOURCE <|-- AUTHORED_ARCHETYPE
AUTHORED_ARCHETYPE <|-- TEMPLATE
AUTHORED_ARCHETYPE <|-- OPERATIONAL_TEMPLATE
ARCHETYPE <|-- TEMPLATE_OVERLAY

@enduml