@startuml
' PlantUML diagram for org.openehr.lang.obsolete-elom.extension.FUNCTION_DEF_EXAMPLE
title FUNCTION_DEF_EXAMPLE Class

class FUNCTION_DEF_EXAMPLE {
  + identifier : String [1..1]
  + evaluation_agent : FUNCTION<> [1..1]
}

abstract class FUNCTION_DEF_EXTERNAL {
  + evaluation_agent : FUNCTION<TUPLE,Any> [1..1]
}

FUNCTION_DEF_EXTERNAL <|-- FUNCTION_DEF_EXAMPLE


@enduml