@startuml

class C_DURATION {
  + years_allowed : Boolean [0..1]
  + months_allowed : Boolean [0..1]
  + weeks_allowed : Boolean [0..1]
  + days_allowed : Boolean [0..1]
  + hours_allowed : Boolean [0..1]
  + minutes_allowed : Boolean [0..1]
  + seconds_allowed : Boolean [0..1]
  + fractional_seconds_allowed : Boolean [0..1]
  + range : Interval<Iso8601_duration> [0..1]
  + assumed_value : Iso8601_duration [0..1]
}

abstract class C_PRIMITIVE  #whitesmoke;line:gray;line.dotted;text:gray {
  + assumed_value : Any [0..1]
  + {abstract} default_value() : Any [1]
  + {abstract} has_assumed_value() : Boolean [1]
  + {abstract} valid_value( a_value : Any [1] ) : Boolean [1]
}

C_PRIMITIVE <|-- C_DURATION


@enduml