@startuml
' PlantUML diagram for org.openehr.am.aom14.archetype.primitive.C_PRIMITIVE
title C_PRIMITIVE Class

abstract class C_PRIMITIVE {
  + assumed_value : Any [0..1]
  + {abstract} default_value() : Any [0..1]
  + {abstract} has_assumed_value() : Boolean [0..1]
  + {abstract} valid_value(Any a_value) : Boolean [0..1]
}


@enduml