@startuml
' PlantUML diagram for org.openehr.am.aom14.archetype.primitive.C_STRING
title C_STRING Class

class C_STRING {
  + pattern : String [0..1]
  + list : List<String> [0..*]
  + list_open : Boolean [1..1]
  + assumed_value : String [0..1]
  + valid_value(String a_value) : Boolean [0..1]
}

abstract class C_PRIMITIVE {
  + assumed_value : Any [0..1]
  + {abstract} default_value() : Any [0..1]
  + {abstract} has_assumed_value() : Boolean [0..1]
  + {abstract} valid_value(Any a_value) : Boolean [0..1]
}

C_PRIMITIVE <|-- C_STRING


@enduml