@startuml
' PlantUML diagram for org.openehr.lang.obsolete-elom.types.TYPE_DEF_DATE
title TYPE_DEF_DATE Class

class TYPE_DEF_DATE {
  + type_name : String [1..1]
  + type_anchor : Any [1..1]
}

abstract class EL_TYPE_DEF {
  + type_name : String [1..1]
  + type_anchor : Any [1..1]
}

EL_TYPE_DEF <|-- TYPE_DEF_DATE


@enduml