@startuml
' PlantUML diagram for org.openehr.am.aom2.persistence.constraint_model.P_C_COMPLEX_OBJECT_PROXY
title P_C_COMPLEX_OBJECT_PROXY Class

class P_C_COMPLEX_OBJECT_PROXY {
  + target_path : String [1..1]
}

abstract class P_C_OBJECT {
  + rm_type_name : String [1..1]
  + occurrences : String [0..1]
  + node_id : String [1..1]
  + is_deprecated : Boolean [0..1]
  + specialisation_depth() : Integer [0..1]
}

abstract class P_ARCHETYPE_CONSTRAINT {
}

P_ARCHETYPE_CONSTRAINT <|-- P_C_OBJECT

P_C_OBJECT <|-- P_C_COMPLEX_OBJECT_PROXY


@enduml