@startuml
' PlantUML diagram for org.openehr.lang.beom.types.EXPR_TYPE_DEF
title EXPR_TYPE_DEF Class

abstract class EXPR_TYPE_DEF {
  + type_name : String [1..1]
  + type_anchor : Any [1..1]
}


@enduml