@startuml
' PlantUML diagram for org.openehr.am.aom14.archetype.assertion.EXPR_LEAF
title EXPR_LEAF Class

class EXPR_LEAF {
  + reference_type : String [1..1]
  + item : Any [1..1]
}

abstract class EXPR_ITEM {
  + type : String [1..1]
}

EXPR_ITEM <|-- EXPR_LEAF


@enduml