@startuml

class FEEDER_AUDIT {
  + originating_system_item_ids : List<DV_IDENTIFIER> [*]
  + feeder_system_item_ids : List<DV_IDENTIFIER> [*]
  + original_content : DV_ENCAPSULATED [0..1]
  + originating_system_audit : FEEDER_AUDIT_DETAILS [1]
  + feeder_system_audit : FEEDER_AUDIT_DETAILS [0..1]
}


@enduml