@startuml
' PlantUML diagram for org.openehr.lang.bmm.core.BMM_FORMAL_ELEMENT
title BMM_FORMAL_ELEMENT Class

abstract class BMM_FORMAL_ELEMENT {
  + type : BMM_TYPE [1..1]
  + is_nullable : Boolean [0..1]
  + {abstract} signature() : BMM_SIGNATURE [0..1]
  + is_boolean() : Boolean [0..1]
}

abstract class BMM_MODEL_ELEMENT {
  + documentation : String [0..1]
}

class BMM_DEFINITIONS {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ELEMENT

BMM_MODEL_ELEMENT <|-- BMM_FORMAL_ELEMENT


@enduml