@startuml
' PlantUML diagram for org.openehr.base.foundation_types.time.Iso8601_duration
title Iso8601_duration Class

class Iso8601_duration {
  + seconds() : Integer [0..1]
  + fractional_seconds() : Real [0..1]
  + is_decimal_sign_comma() : Boolean [0..1]
  + is_partial() : Boolean [0..1]
  + is_extended() : Boolean [0..1]
  + months() : Integer [0..1]
  + years() : Integer [0..1]
  + weeks() : Integer [0..1]
  + to_seconds() : Real [0..1]
  + minutes() : Integer [0..1]
  + hours() : Integer [0..1]
  + days() : Integer [0..1]
  + as_string() : String [0..1]
}

abstract class Iso8601_type {
  + value : String [1..1]
  + {abstract} is_partial() : Boolean [0..1]
  + {abstract} is_extended() : Boolean [0..1]
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- Iso8601_type

Iso8601_type <|-- Iso8601_duration


@enduml