@startuml
' PlantUML diagram for org.openehr.base.foundation_types.time.Iso8601_date_time
title Iso8601_date_time Class

class Iso8601_date_time {
  + year() : Integer [0..1]
  + month() : Integer [0..1]
  + day() : Integer [0..1]
  + hour() : Integer [0..1]
  + minute() : Integer [0..1]
  + second() : Integer [0..1]
  + fractional_second() : Real [0..1]
  + timezone() : Iso8601_timezone [0..1]
  + month_unknown() : Boolean [0..1]
  + day_unknown() : Boolean [0..1]
  + minute_unknown() : Boolean [0..1]
  + second_unknown() : Boolean [0..1]
  + is_decimal_sign_comma() : Boolean [0..1]
  + is_partial() : Boolean [0..1]
  + is_extended() : Boolean [0..1]
  + has_fractional_second() : Boolean [0..1]
  + as_string() : String [0..1]
}

abstract class Iso8601_type {
  + value : String [1..1]
  + {abstract} is_partial() : Boolean [0..1]
  + {abstract} is_extended() : Boolean [0..1]
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- Iso8601_type

Iso8601_type <|-- Iso8601_date_time


@enduml