@startuml

class Time_Definitions {
  + valid_year( y : Integer [1] ) : Boolean [1]
  + valid_month( m : Integer [1] ) : Boolean [1]
  + valid_day( y : Integer [1], m : Integer [1], d : Integer [1] ) : Boolean [1]
  + valid_hour( h : Integer [1], m : Integer [1], s : Integer [1] ) : Boolean [1]
  + valid_minute( m : Integer [1] ) : Boolean [1]
  + valid_second( s : Integer [1] ) : Boolean [1]
  + valid_fractional_second( fs : Double [1] ) : Boolean [1]
  + valid_iso8601_date( s : String [1] ) : Boolean [1]
  + valid_iso8601_time( s : String [1] ) : Boolean [1]
  + valid_iso8601_date_time( s : String [1] ) : Boolean [1]
  + valid_iso8601_duration( s : String [1] ) : Boolean [1]
}


@enduml