@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_CASE_TABLE
title EL_CASE_TABLE Class

class EL_CASE_TABLE {
  + items : List<EL_CASE> [1..*]
  + input : EL_SIMPLE [1..1]
}

abstract class EL_DECISION_TABLE {
  + else : EL_EXPRESSION [1..1]
  + items : List<EL_DECISION_BRANCH> [1..*]
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_DECISION_TABLE

EL_DECISION_TABLE <|-- EL_CASE_TABLE


@enduml