@startuml

class EL_CONDITIONAL_EXPRESSION {
  + condition : EL_SIMPLE [1]
}

abstract class EL_DECISION_BRANCH  #whitesmoke;line:gray;line.dotted;text:gray {
  + result : EL_EXPRESSION [1]
}

EL_DECISION_BRANCH <|-- EL_CONDITIONAL_EXPRESSION


@enduml