@startuml

class EL_FUNCTION_CALL {
  + agent : EL_FUNCTION_AGENT [1]
  + eval_type() : BMM_TYPE [1]
}

abstract class EL_SCOPED_REF  #whitesmoke;line:gray;line.dotted;text:gray {
  + scope : EL_INSTANCE_REF [0..1]
}

abstract class EL_INSTANCE_REF  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class EL_TERMINAL  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class EL_SIMPLE  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class EL_EXPRESSION  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} eval_type() : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

EL_EXPRESSION <|-- EL_SIMPLE

EL_SIMPLE <|-- EL_TERMINAL

EL_TERMINAL <|-- EL_INSTANCE_REF

EL_INSTANCE_REF <|-- EL_SCOPED_REF

EL_SCOPED_REF <|-- EL_FUNCTION_CALL

abstract class EL_AGENT_CALL  #whitesmoke;line:gray;line.dotted;text:gray {
  + agent : EL_AGENT [1]
}

EL_AGENT_CALL <|-- EL_FUNCTION_CALL


@enduml