@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_INSTANCE_REF
title EL_INSTANCE_REF Class

abstract class EL_INSTANCE_REF {
}

abstract class EL_TERMINAL {
}

abstract class EL_SIMPLE {
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_SIMPLE

EL_SIMPLE <|-- EL_TERMINAL

EL_TERMINAL <|-- EL_INSTANCE_REF


@enduml