@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_SIMPLE
title EL_SIMPLE Class

abstract class EL_SIMPLE {
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_SIMPLE


@enduml