@startuml
' PlantUML diagram for org.openehr.base.foundation_types.iso8601_time.Iso8601_timezone
title Iso8601_timezone Class

class Iso8601_timezone {
  + minute_unknown() : Boolean [0..1]
  + is_partial() : Boolean [0..1]
  + is_extended() : Boolean [0..1]
  + as_string() : String [0..1]
  + is_gmt() : Boolean [0..1]
  + as_timezone() : Timezone [0..1]
}

abstract class Iso8601_type {
  + value : String [1..1]
  + {abstract} is_partial() : Boolean [0..1]
  + {abstract} is_extended() : Boolean [0..1]
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- Iso8601_type

Iso8601_type <|-- Iso8601_timezone

abstract class ITimezone {
  + hour() : Integer [0..1]
  + minute() : Integer [0..1]
  + sign() : Integer [0..1]
}

abstract class Temporal {
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- Temporal

class Time_Definitions {
  + valid_year(Integer y) : Boolean [0..1]
  + valid_month(Integer m) : Boolean [0..1]
  + valid_day(Integer y, Integer m, Integer d) : Boolean [0..1]
  + valid_hour(Integer h, Integer m, Integer s) : Boolean [0..1]
  + valid_minute(Integer m) : Boolean [0..1]
  + valid_second(Integer s) : Boolean [0..1]
  + valid_fractional_second(Double fs) : Boolean [0..1]
}

Time_Definitions <|-- Temporal

Temporal <|-- ITimezone

ITimezone <|-- Iso8601_timezone


@enduml