=== BMM_DEFINITIONS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_DEFINITIONS*

h|*Description*
2+a|Definitions used by all BMM packages.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/base_types.html#_basic_definitions_class[BASIC_DEFINITIONS^]`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*Any_class* (): `<<_bmm_simple_class_class,BMM_SIMPLE_CLASS>>`
a|built-in class definition corresponding to the top `Any' class.

h|*1..1*
|*Any_type* (): `<<_bmm_simple_type_class,BMM_SIMPLE_TYPE>>`
a|Built-in type definition corresponding to the top `Any' type.

h|*1..1*
|*create_schema_id* ( +
a_model_publisher: `link:/releases/BASE/{base_release}/foundation_types.html#_any_class[Any^][1]`, +
a_schema_name: `link:/releases/BASE/{base_release}/foundation_types.html#_any_class[Any^][1]`, +
a_model_release: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Create schema id, formed from:

`a_model_publisher '-' a_schema_name '-' a_model_release`

e.g. `openehr_rm_1.0.3`, `openehr_test_1.0.1`, `iso_13606_1_2008_2.1.2`.
|===
