@startuml

class MESSAGE {
  + audit : AUDIT_DETAILS [1]
  + author : PARTY_PROXY [1]
  + content : MESSAGE_CONTENT [1]
  + signature : String [0..1]
}

class ADDRESSED_MESSAGE {
  + sender : String [1]
  + sender_reference : String [1]
  + addressees : List<String> [1..*]
  + urgency : Integer [0..1]
  + message : MESSAGE [1]
}

abstract class MESSAGE_CONTENT {
}


@enduml