@startuml
' PlantUML diagram for org.openehr.am.aom2.constraint_model.ARCHETYPE_CONSTRAINT
title ARCHETYPE_CONSTRAINT Class

abstract class ARCHETYPE_CONSTRAINT {
  + {abstract} is_subset_of(ARCHETYPE_CONSTRAINT other) : Boolean [0..1]
  + {abstract} is_valid() : Boolean [0..1]
  + path() : String [0..1]
  + has_path(String a_path) : Boolean [0..1]
}


@enduml