@startuml

abstract class AUTHORED_RESOURCE {
  + original_language : Terminology_code [1]
  + is_controlled : Boolean [0..1]
  + description : RESOURCE_DESCRIPTION [0..1]
  + uid : UUID [0..1]
  + annotations : RESOURCE_ANNOTATIONS [0..1]
  + translations : Hash<String,TRANSLATION_DETAILS> [0..1]
  + current_revision() : String [1]
  + languages_available() : List<String> [1..*]
}


@enduml