@startuml
' PlantUML diagram for org.openehr.rm.data_types.basic.DV_IDENTIFIER
title DV_IDENTIFIER Class

class DV_IDENTIFIER {
  + issuer : String [0..1]
  + assigner : String [0..1]
  + id : String [1..1]
  + type : String [0..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_IDENTIFIER


@enduml