@startuml

abstract class EXPRESSION {
  + {abstract} type() : EXPR_TYPE_DEF [1]
}

abstract class EXPR_VALUE  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} value() : Any [1]
}

EXPR_VALUE <|-- EXPRESSION


@enduml