@startuml

class VARIABLE_DECLARATION {
  + name : String [1]
  + type : EXPR_TYPE_DEF [1]
}

abstract class STATEMENT  #whitesmoke;line:gray;line.dotted;text:gray {
}

STATEMENT <|-- VARIABLE_DECLARATION


@enduml