@startuml
' PlantUML diagram for org.openehr.lang.bmm.statement.BMM_STATEMENT
title BMM_STATEMENT Class

abstract class BMM_STATEMENT {
}

abstract class BMM_STATEMENT_ITEM {
}

abstract class BMM_ROUTINE_BODY {
}

BMM_ROUTINE_BODY <|-- BMM_STATEMENT_ITEM

BMM_STATEMENT_ITEM <|-- BMM_STATEMENT


@enduml