@startuml

class BMM_ASSIGNMENT {
  + target : EL_INSTANTIABLE_REF [1]
  + source : EL_EXPRESSION [1]
}

abstract class BMM_SIMPLE_STATEMENT  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class BMM_STATEMENT  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class BMM_STATEMENT_ITEM  #whitesmoke;line:gray;line.dotted;text:gray {
}

abstract class BMM_ROUTINE_BODY  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_ROUTINE_BODY <|-- BMM_STATEMENT_ITEM

BMM_STATEMENT_ITEM <|-- BMM_STATEMENT

BMM_STATEMENT <|-- BMM_SIMPLE_STATEMENT

BMM_SIMPLE_STATEMENT <|-- BMM_ASSIGNMENT


@enduml