@startuml
' PlantUML diagram for org.openehr.lang.bmm.statement.BMM_STATEMENT_ITEM
title BMM_STATEMENT_ITEM Class

abstract class BMM_STATEMENT_ITEM {
}

abstract class BMM_ROUTINE_BODY {
}

BMM_ROUTINE_BODY <|-- BMM_STATEMENT_ITEM


@enduml