@startuml

class VALUE_SET {
}

abstract class TERMINOLOGY_RELATION  #whitesmoke;line:gray;line.dotted;text:gray {
  + id : String [1]
  + members : List<String> [1..*]
}

TERMINOLOGY_RELATION <|-- VALUE_SET


@enduml