@startuml
' PlantUML diagram for org.openehr.am.aom2.terminology.VALUE_SET
title VALUE_SET Class

class VALUE_SET {
}

abstract class TERMINOLOGY_RELATION {
  + id : String [1..1]
  + members : List<String> [1..*]
}

TERMINOLOGY_RELATION <|-- VALUE_SET


@enduml