@startuml

class Hash <K, V> {
  + has_key( a_key : K [1] ) : Boolean [1]
  + item( a_key : K [1] ) : V [1]
}

abstract class Aggregate <T> {
  + {abstract} has( v : T [1] ) : Boolean [1]
  + {abstract} count() : Integer [1]
  + {abstract} is_empty() : Boolean [1]
}

class List <T> {
  + first() : T [1]
  + last() : T [1]
}

class Set <T> {
}

class Array <T> {
}

Aggregate <|-- Hash
Aggregate <|-- List
Aggregate <|-- Set
Aggregate <|-- Array

@enduml