@startuml

abstract class AUTHORED_RESOURCE {
  + original_language : Terminology_code [1]
  + is_controlled : Boolean [0..1]
  + description : RESOURCE_DESCRIPTION [0..1]
  + uid : UUID [0..1]
  + annotations : RESOURCE_ANNOTATIONS [0..1]
  + translations : Hash<String,TRANSLATION_DETAILS> [0..1]
  + current_revision() : String [1]
  + languages_available() : List<String> [1..*]
}

class RESOURCE_DESCRIPTION {
  + original_author : Hash<String,String> [1]
  + original_namespace : String [0..1]
  + original_publisher : String [0..1]
  + other_contributors : List<String> [*]
  + lifecycle_state : Terminology_code [1]
  + parent_resource : AUTHORED_RESOURCE [1]
  + custodian_namespace : String [0..1]
  + custodian_organisation : String [0..1]
  + copyright : String [0..1]
  + licence : String [0..1]
  + ip_acknowledgements : Hash<String,String> [0..1]
  + references : Hash<String,String> [0..1]
  + resource_package_uri : String [0..1]
  + conversion_details : Hash<String,String> [0..1]
  + other_details : Hash<String,String> [0..1]
  + details : Hash<String,RESOURCE_DESCRIPTION_ITEM> [0..1]
}

class TRANSLATION_DETAILS {
  + language : Terminology_code [1]
  + author : Hash<String,String> [1]
  + accreditaton : String [0..1]
  + other_details : Hash<String,String> [0..1]
  + version_last_translated : String [0..1]
}

class RESOURCE_DESCRIPTION_ITEM {
  + language : Terminology_code [1]
  + purpose : String [1]
  + keywords : List<String> [*]
  + use : String [0..1]
  + misuse : String [0..1]
  + original_resource_uri : Hash<String,String> [0..1]
  + other_details : Hash<String,String> [0..1]
}

class RESOURCE_ANNOTATIONS {
  + documentation : Hash<String,Hash<String,Hash<String,String>>> [1]
}


@enduml