@startuml
' PlantUML diagram for org.openehr.base.bmm.core
title core Package

abstract class BMM_TYPE {
  + {abstract} effective_base_class() : BMM_CLASS [0..1]
  + {abstract} type_name() : String [0..1]
  + {abstract} has_subtypes() : Boolean [0..1]
  + {abstract} subtypes() : List<String> [0..*]
  + {abstract} flattened_type_list() : List<String> [0..*]
  + type_signature() : String [0..1]
  + is_primitive() : Boolean [0..1]
  + entity_metatype() : String [0..1]
}

abstract class BMM_CLASS {
  + name : String [1..1]
  + ancestors : List<String> [0..*]
  + package : BMM_PACKAGE [1..1]
  + properties : Hash<String,BMM_PROPERTY> [0..1]
  + source_schema_id : String [1..1]
  + immediate_descendants : List<BMM_CLASS> [0..*]
  + is_override : Boolean [1..1]
  + all_ancestors() : List<String> [1..*]
  + all_descendants() : List<String> [1..*]
  + suppliers() : List<String> [1..*]
  + suppliers_non_primitive() : List<String> [1..*]
  + supplier_closure() : List<String> [1..*]
  + package_path() : String [0..1]
  + class_path() : String [0..1]
  + flat_properties() : List<Hash<String,BMM_PROPERTY<BMM_TYPE>>> [1..*]
  + is_primitive() : Boolean [0..1]
  + is_abstract() : Boolean [0..1]
  + {abstract} type() : BMM_DEFINED_TYPE [0..1]
}

class BMM_PROPERTY <<T>> {
  + name : String [1..1]
  + is_mandatory : Boolean [0..1]
  + is_computed : Boolean [0..1]
  + type : T [1..1]
  + is_im_runtime : Boolean [0..1]
  + is_im_infrastructure : Boolean [0..1]
  + is_synthesised_generic : Boolean [0..1]
  + existence() : Multiplicity_interval [0..1]
  + display_name() : String [0..1]
}

class BMM_CONTAINER_TYPE {
  + container_class : BMM_GENERIC_CLASS [1..1]
  + base_type : BMM_UNITARY_TYPE [1..1]
  + type_name() : String [0..1]
  + effective_base_class() : BMM_CLASS [0..1]
  + is_abstract() : Boolean [0..1]
  + entity_metatype() : String [0..1]
  + flattened_type_list() : List<String> [0..*]
  + subtypes() : List<String> [0..*]
  + has_subtypes() : Boolean [0..1]
}

class BMM_GENERIC_TYPE {
  + generic_parameters : List<BMM_UNITARY_TYPE> [1..*]
  + base_class : BMM_GENERIC_CLASS [1..1]
  + type_name() : String [0..1]
  + type_signature() : String [0..1]
  + is_abstract() : Boolean [0..1]
  + flattened_type_list() : List<String> [0..*]
  + subtypes() : List<String> [0..*]
  + has_subtypes() : Boolean [0..1]
  + is_partially_closed() : Boolean [0..1]
  + effective_base_class() : BMM_GENERIC_CLASS [0..1]
}

class BMM_SIMPLE_TYPE {
  + type_name() : String [0..1]
  + is_abstract() : Boolean [0..1]
  + flattened_type_list() : List<String> [0..*]
  + subtypes() : List<String> [0..*]
  + has_subtypes() : Boolean [0..1]
  + effective_base_class() : BMM_SIMPLE_CLASS [0..1]
}

class BMM_ENUMERATION <<T>> {
  + item_names : List<String> [0..*]
  + item_values : T [0..1]
  + entity_metatype() : String [0..1]
  + name_map() : Hash<String,String> [0..1]
}

class BMM_ENUMERATION_STRING {
}

class BMM_ENUMERATION_INTEGER {
}

class BMM_PACKAGE {
  + name : String [1..1]
  + classes : List<BMM_CLASS> [0..*]
  + root_classes() : List<BMM_CLASS> [1..*]
  + path() : String [0..1]
}

class BMM_PARAMETER_TYPE {
  + name : String [1..1]
  + type_constraint : BMM_DEFINED_TYPE [0..1]
  + inheritance_precursor : BMM_PARAMETER_TYPE [0..1]
  + flattened_conforms_to_type() : String [0..1]
  + effective_conforms_to_type() : BMM_CLASS [0..1]
  + type_signature() : String [0..1]
  + is_primitive() : Boolean [0..1]
  + is_abstract() : Boolean [0..1]
  + entity_metatype() : String [0..1]
  + effective_base_class() : BMM_CLASS [0..1]
  + has_subtypes() : Boolean [0..1]
  + subtypes() : List<String> [0..*]
  + type_name() : String [0..1]
  + flattened_type_list() : List<String> [0..*]
}

abstract class BMM_ENTITY {
  + {abstract} entity_category() : String [0..1]
  + {abstract} entity_metatype() : String [0..1]
  + {abstract} is_abstract() : Boolean [0..1]
  + {abstract} is_primitive() : Boolean [0..1]
}

class BMM_CONTAINER_PROPERTY {
  + type : BMM_CONTAINER_TYPE [1..1]
  + cardinality : Multiplicity_interval [0..1]
  + display_name() : String [0..1]
}

class BMM_MODEL {
  + class_definitions : Hash<String,BMM_CLASS> [0..1]
  + model_name : String [1..1]
  + model_id() : String [0..1]
  + class_definition(String a_name) : BMM_CLASS [0..1]
  + type_definition() : BMM_CLASS [0..1]
  + has_class_definition(String a_class_name) : Boolean [0..1]
  + has_type_definition(String a_type_name) : Boolean [0..1]
  + enumeration_definition(String a_name) : BMM_ENUMERATION [0..1]
  + primitive_types() : List<String> [1..*]
  + enumeration_types() : List<String> [1..*]
  + property_definition() : BMM_PROPERTY [0..1]
  + ms_conformant_property_type(String a_bmm_type_name, String a_bmm_property_name, String a_ms_property_name) : Boolean [0..1]
  + property_definition_at_path() : BMM_PROPERTY [0..1]
  + class_definition_at_path(String a_type_name, String a_prop_path) : BMM_CLASS [0..1]
  + all_ancestor_classes(String a_class) : List<String> [1..*]
  + is_descendant_of(String a_class_name, String a_parent_class_name) : Boolean [0..1]
  + type_conforms_to(String a_desc_type, String an_anc_type) : Boolean [0..1]
  + any_class_definition() : BMM_SIMPLE_CLASS [0..1]
  + any_type_definition() : BMM_SIMPLE_TYPE [0..1]
}

class BMM_PACKAGE_CONTAINER {
  + packages : Hash<String,BMM_PACKAGE> [0..1]
  + package_at_path(String a_path) : BMM_PACKAGE [1..1]
  + do_recursive_packages(PROCEDURE action) : void [0..1]
  + has_package_path(String a_path) : Boolean [0..1]
}

class BMM_GENERIC_CLASS {
  + generic_parameters : Hash<String,BMM_PARAMETER_TYPE> [1..1]
  + suppliers() : List<String> [1..*]
  + entity_metatype() : String [0..1]
  + type() : BMM_GENERIC_TYPE [0..1]
  + generic_parameter_conformance_type(String a_name) : String [0..1]
}

class BMM_DEFINITIONS {
}

abstract class BMM_MODEL_ELEMENT {
  + documentation : String [0..1]
}

abstract class BMM_UNITARY_TYPE {
}

class BMM_INDEXED_CONTAINER_TYPE {
  + index_type : BMM_SIMPLE_TYPE [1..1]
}

abstract class BMM_DEFINED_TYPE {
  + base_class : BMM_CLASS [1..1]
}

class BMM_SIMPLE_CLASS {
  + type() : BMM_SIMPLE_TYPE [0..1]
  + entity_metatype() : String [0..1]
}

class BMM_MODEL_METADATA {
  + rm_publisher : String [1..1]
  + rm_release : String [1..1]
}

BMM_ENTITY <|-- BMM_TYPE
BMM_ENTITY <|-- BMM_CLASS
BMM_MODEL_ELEMENT <|-- BMM_CLASS
BMM_MODEL_ELEMENT <|-- BMM_PROPERTY
BMM_TYPE <|-- BMM_CONTAINER_TYPE
BMM_DEFINED_TYPE <|-- BMM_GENERIC_TYPE
BMM_DEFINED_TYPE <|-- BMM_SIMPLE_TYPE
BMM_SIMPLE_CLASS <|-- BMM_ENUMERATION
BMM_ENUMERATION <|-- BMM_ENUMERATION_STRING
BMM_ENUMERATION <|-- BMM_ENUMERATION_INTEGER
BMM_PACKAGE_CONTAINER <|-- BMM_PACKAGE
BMM_UNITARY_TYPE <|-- BMM_PARAMETER_TYPE
BMM_DEFINITIONS <|-- BMM_ENTITY
BMM_PROPERTY <|-- BMM_CONTAINER_PROPERTY
BMM_PACKAGE_CONTAINER <|-- BMM_MODEL
BMM_MODEL_METADATA <|-- BMM_MODEL
BMM_MODEL_ELEMENT <|-- BMM_PACKAGE_CONTAINER
BMM_CLASS <|-- BMM_GENERIC_CLASS
BMM_DEFINITIONS <|-- BMM_MODEL_ELEMENT
BMM_TYPE <|-- BMM_UNITARY_TYPE
BMM_CONTAINER_TYPE <|-- BMM_INDEXED_CONTAINER_TYPE
BMM_UNITARY_TYPE <|-- BMM_DEFINED_TYPE
BMM_CLASS <|-- BMM_SIMPLE_CLASS

@enduml