@startuml

class BMM_INTEGER_VALUE {
  + value : Integer [1]
}

class BMM_PRIMITIVE_VALUE  #whitesmoke;line:gray;line.dotted;text:gray {
  + type : BMM_SIMPLE_TYPE [1]
}

abstract class BMM_UNITARY_VALUE  #whitesmoke;line:gray;line.dotted;text:gray {
  + type : BMM_UNITARY_TYPE [1]
}

abstract class BMM_LITERAL_VALUE  #whitesmoke;line:gray;line.dotted;text:gray {
  + value_literal : String [1]
  + value : Any [0..1]
  + syntax : String [0..1]
}

abstract class BMM_TYPED  #whitesmoke;line:gray;line.dotted;text:gray {
  + type : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

BMM_TYPED <|-- BMM_LITERAL_VALUE

BMM_LITERAL_VALUE <|-- BMM_UNITARY_VALUE

BMM_UNITARY_VALUE <|-- BMM_PRIMITIVE_VALUE

BMM_PRIMITIVE_VALUE <|-- BMM_INTEGER_VALUE


@enduml