@startuml

class BMM_CONTAINER_VALUE {
  + type : BMM_CONTAINER_TYPE [1]
}

abstract class BMM_LITERAL_VALUE  #whitesmoke;line:gray;line.dotted;text:gray {
  + value_literal : String [1]
  + value : Any [0..1]
  + syntax : String [0..1]
}

abstract class BMM_TYPED  #whitesmoke;line:gray;line.dotted;text:gray {
  + type : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

BMM_TYPED <|-- BMM_LITERAL_VALUE

BMM_LITERAL_VALUE <|-- BMM_CONTAINER_VALUE


@enduml