@startuml

class BMM_ROUTINE_EXTERNAL {
  + meta_data : Hash<String,String> [1]
  + argument_mapping : Hash<String,String> [0..1]
}

abstract class BMM_ROUTINE_BODY  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_ROUTINE_BODY <|-- BMM_ROUTINE_EXTERNAL


@enduml