@startuml
' PlantUML diagram for org.openehr.lang.bmm.core.feature.BMM_TYPED_FEATURE
title BMM_TYPED_FEATURE Class

abstract class BMM_TYPED_FEATURE {
  + is_nullable : Boolean [0..1]
}

abstract class BMM_TYPED {
  + type : BMM_TYPE [1..1]
  + is_boolean() : Boolean [0..1]
}

BMM_TYPED <|-- BMM_TYPED_FEATURE


@enduml