@startuml
' PlantUML diagram for org.openehr.am.p_aom2.terminology.P_ARCHETYPE_TERMINOLOGY
title P_ARCHETYPE_TERMINOLOGY Class

class P_ARCHETYPE_TERMINOLOGY {
  + is_differential : Boolean [1..1]
  + original_language : String [1..1]
  + term_definitions : Hash<String,Hash<String,ARCHETYPE_TERM>> [1..1]
  + term_bindings : Hash<String,Hash<String,Uri>> [0..1]
  + value_sets : Hash<String,VALUE_SET> [0..1]
}


@enduml