@startuml

abstract class EL_CONSTRAINED {
  + base_expression : EL_EXPRESSION [1]
}

abstract class EL_EXPRESSION  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} eval_type() : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

EL_EXPRESSION <|-- EL_CONSTRAINED


@enduml