@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_DECISION_TABLE
title EL_DECISION_TABLE Class

abstract class EL_DECISION_TABLE <<T>> {
  + items : List<EL_DECISION_BRANCH<T>> [1..*]
  + else : T [1..1]
}

abstract class EL_TERMINAL {
}

abstract class EL_SIMPLE {
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_SIMPLE

EL_SIMPLE <|-- EL_TERMINAL

EL_TERMINAL <|-- EL_DECISION_TABLE


@enduml