@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_OPERATOR
title EL_OPERATOR Class

abstract class EL_OPERATOR {
  + precedence_overridden : Boolean [0..1]
  + symbol : String [0..1]
  + call : EL_FUNCTION_CALL [1..1]
  + operator_definition() : BMM_OPERATOR [0..1]
  + equivalent_call() : EL_FUNCTION_CALL [0..1]
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_OPERATOR


@enduml