@startuml

abstract class EL_OPERATOR {
  + precedence_overridden : Boolean [0..1]
  + symbol : String [0..1]
  + call : EL_FUNCTION_CALL [1]
  + operator_definition() : BMM_OPERATOR [1]
  + equivalent_call() : EL_FUNCTION_CALL [1]
}

abstract class EL_EXPRESSION  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} eval_type() : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

EL_EXPRESSION <|-- EL_OPERATOR


@enduml