@startuml
' PlantUML diagram for org.openehr.lang.bmm.expression.EL_PREDICATE
title EL_PREDICATE Class

abstract class EL_PREDICATE {
  + operand : EL_VALUE_GENERATOR [1..1]
  + eval_type() : BMM_SIMPLE_TYPE [0..1]
}

abstract class EL_SIMPLE {
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [0..1]
  + is_boolean() : Boolean [0..1]
}

EL_EXPRESSION <|-- EL_SIMPLE

EL_SIMPLE <|-- EL_PREDICATE


@enduml