[cols="^1,3,5"]
|===
h|*Class*
2+^h|*RESOURCE_DESCRIPTION*

h|*Description*
2+a|Defines the descriptive meta-data of a resource.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*original_author*: `link:/classes/Hash[Hash]<String,String>`
a|Original author of this resource, with all relevant details, including organisation.

h|*0..1*
|*original_namespace*: `link:/classes/String[String]`
a|Namespace of original author's organisation, in reverse internet form, if applicable.

h|*0..1*
|*original_publisher*: `link:/classes/String[String]`
a|Plain text name of organisation that originally published this artefact, if any.

h|*0..**
|*other_contributors*: `link:/classes/List[List]<link:/classes/String[String]>`
a|Other contributors to the resource, each listed in "name <email>"  form.

h|*1..1*
|*lifecycle_state*: `link:/classes/Terminology_code[Terminology_code]`
a|Lifecycle state of the resource, typically including states such as: initial, in_development, in_review, published, superseded, obsolete.

h|*1..1*
|*parent_resource*: `link:/classes/AUTHORED_RESOURCE[AUTHORED_RESOURCE]`
a|Reference to owning resource.

h|*0..1*
|*custodian_namespace*: `link:/classes/String[String]`
a|Namespace in reverse internet id form, of current custodian organisation.

h|*0..1*
|*custodian_organisation*: `link:/classes/String[String]`
a|Plain text name of current custodian organisation.

h|*0..1*
|*copyright*: `link:/classes/String[String]`
a|Optional copyright statement for the resource as a knowledge resource.

h|*0..1*
|*licence*: `link:/classes/String[String]`
a|Licence of current artefact, in format "short licence name <URL of licence>", e.g. "Apache 2.0 License <http://www.apache.org/licenses/LICENSE-2.0.html>"

h|*0..1*
|*ip_acknowledgements*: `link:/classes/Hash[Hash]<String,String>`
a|List of acknowledgements of other IP directly referenced in this archetype, typically terminology codes, ontology ids etc. Recommended keys are the widely known name or namespace for the IP source, as shown in the following example:

----
ip_acknowledgements = <
    ["loinc"] = <"This content from LOINC® is copyright © 1995 Regenstrief Institute, Inc. and the LOINC Committee, and available at no cost under the license at http://loinc.org/terms-of-use">
    ["snomedct"] = <"Content from SNOMED CT® is copyright © 2007 IHTSDO <ihtsdo.org>">
>
----

h|*0..1*
|*references*: `link:/classes/Hash[Hash]<String,String>`
a|List of references of material on which this artefact is based, as a keyed list of strings. The keys should be in a standard citation format.

h|*0..1*
|*resource_package_uri*: `link:/classes/String[String]`
a|URI of package to which this resource belongs.

h|*0..1*
|*conversion_details*: `link:/classes/Hash[Hash]<String,String>`
a|Details related to conversion process that generated this model from an original, if relevant, as a list of name/value pairs. Typical example with recommended tags:

----
conversion_details = <
    ["source_model"] = <"CEM model xyz <http://location.in.clinicalelementmodels.com>">
    ["tool"] = <"cem2adl v6.3.0">
    ["time"] = <"2014-11-03T09:05:00">
>
----

h|*0..1*
|*other_details*: `link:/classes/Hash[Hash]<String,String>`
a|Additional non-language-sensitive resource meta-data, as a list of name/value pairs.

h|*0..1*
|*details*: `link:/classes/Hash[Hash]<String,RESOURCE_DESCRIPTION_ITEM>`
a|Details of all parts of resource description that are natural language-dependent, keyed by language code.
|===
