@startuml
' PlantUML diagram for org.openehr.lang.bmm.statement.BMM_ASSIGNMENT
title BMM_ASSIGNMENT Class

class BMM_ASSIGNMENT {
  + target : EL_VALUE_GENERATOR [1..1]
  + source : EL_EXPRESSION [1..1]
}

abstract class BMM_SIMPLE_STATEMENT {
}

abstract class BMM_STATEMENT {
}

abstract class BMM_STATEMENT_ITEM {
}

abstract class BMM_ROUTINE_BODY {
}

BMM_ROUTINE_BODY <|-- BMM_STATEMENT_ITEM

BMM_STATEMENT_ITEM <|-- BMM_STATEMENT

BMM_STATEMENT <|-- BMM_SIMPLE_STATEMENT

BMM_SIMPLE_STATEMENT <|-- BMM_ASSIGNMENT


@enduml