@startuml
' PlantUML diagram for org.openehr.am.aom14.archetype.primitive.C_BOOLEAN
title C_BOOLEAN Class

class C_BOOLEAN {
  + true_valid : Boolean [1..1]
  + false_valid : Boolean [1..1]
  + assumed_value : Boolean [0..1]
}

abstract class C_PRIMITIVE {
  + assumed_value : Any [0..1]
  + {abstract} default_value() : Any [0..1]
  + {abstract} has_assumed_value() : Boolean [0..1]
  + {abstract} valid_value(Any a_value) : Boolean [0..1]
}

C_PRIMITIVE <|-- C_BOOLEAN


@enduml