@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types.Integer
title Integer Class

class Integer {
  + add(Integer other) : Integer [0..1]
  + subtract(Integer other) : Integer [0..1]
  + multiply(Integer other) : Integer [0..1]
  + divide(Integer other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + modulo(Integer mod) : Integer [0..1]
  + less_than(Integer other) : Boolean [0..1]
  + negative() : Integer [0..1]
  + is_equal(Integer other) : Boolean [0..1]
  + equal(Integer other) : Boolean [0..1]
}

abstract class Ordered_Numeric {
}

abstract class Ordered {
  + {abstract} infix <(Ordered other) : Boolean [0..1]
}

Ordered <|-- Ordered_Numeric

abstract class Numeric {
  + {abstract} infix *(Numeric other) : Numeric [0..1]
  + {abstract} infix +(Numeric other) : Numeric [0..1]
  + {abstract} infix -(Numeric other) : Numeric [0..1]
}

Numeric <|-- Ordered_Numeric

Ordered_Numeric <|-- Integer


@enduml