@startuml
' PlantUML diagram for org.openehr.lang.bmm.core.literal_value.BMM_INDEXED_CONTAINER_VALUE
title BMM_INDEXED_CONTAINER_VALUE Class

class BMM_INDEXED_CONTAINER_VALUE {
}

abstract class BMM_LITERAL_VALUE {
  + value_literal : String [1..1]
  + value : Any [0..1]
  + syntax : String [0..1]
}

abstract class BMM_TYPED {
  + type : BMM_TYPE [1..1]
  + is_boolean() : Boolean [0..1]
}

BMM_TYPED <|-- BMM_LITERAL_VALUE

BMM_LITERAL_VALUE <|-- BMM_INDEXED_CONTAINER_VALUE


@enduml