@startuml
' PlantUML diagram for org.openehr.rm.ehr_extract.common.EXTRACT_ITEM
title EXTRACT_ITEM Class

abstract class EXTRACT_ITEM {
}

abstract class LOCATABLE {
  + name : DV_TEXT [1..1]
  + archetype_node_id : String [1..1]
  + uid : UID_BASED_ID [0..1]
  + links : List<LINK> [0..*]
  + archetype_details : ARCHETYPED [0..1]
  + feeder_audit : FEEDER_AUDIT [0..1]
  + concept() : DV_TEXT [0..1]
  + is_archetype_root() : Boolean [0..1]
}

abstract class PATHABLE {
  + parent() : PATHABLE [0..1]
  + item_at_path(String a_path) : Any [0..1]
  + items_at_path(String a_path) : List<Any> [1..*]
  + path_exists(String a_path) : Boolean [0..1]
  + path_unique(String a_path) : Boolean [0..1]
  + path_of_item(PATHABLE a_loc) : String [0..1]
}

PATHABLE <|-- LOCATABLE

LOCATABLE <|-- EXTRACT_ITEM


@enduml