@startuml

class OPENEHR_DEFINITIONS {
}

class BASIC_DEFINITIONS {
}

enum VALIDITY_KIND {
  mandatory 
  optional 
  prohibited 
}

enum VERSION_STATUS {
  alpha 
  beta 
  release_candidate 
  released 
  build 
}

BASIC_DEFINITIONS <|-- OPENEHR_DEFINITIONS

@enduml