@startuml

class RESOURCE_DESCRIPTION_ITEM {
  + language : CODE_PHRASE [1]
  + purpose : String [1]
  + keywords : List<String> [*]
  + use : String [0..1]
  + misuse : String [0..1]
  + copyright : String [0..1]
  + original_resource_uri : Hash<String,String> [0..1]
  + other_details : Hash<String,String> [0..1]
}


@enduml