@startuml

class Iso8601_time {
  + hour() : Integer [1]
  + minute() : Integer [1]
  + second() : Integer [1]
  + fractional_second() : Real [1]
  + timezone() : Iso8601_timezone [1]
  + minute_unknown() : Boolean [1]
  + second_unknown() : Boolean [1]
  + is_decimal_sign_comma() : Boolean [1]
  + is_partial() : Boolean [1]
  + is_extended() : Boolean [1]
  + has_fractional_second() : Boolean [1]
  + as_string() : String [1]
  + add( a_diff : Iso8601_duration [1] ) : Iso8601_time [1]
  + subtract( a_diff : Iso8601_duration [1] ) : Iso8601_time [1]
  + diff( a_time : Iso8601_time [1] ) : Iso8601_duration [1]
}

abstract class Iso8601_type  #whitesmoke;line:gray;line.dotted;text:gray {
  + value : String [1]
  + {abstract} is_partial() : Boolean [1]
  + {abstract} is_extended() : Boolean [1]
}

abstract class Ordered  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} infix <( other : Ordered [1] ) : Boolean [1]
}

Ordered <|-- Iso8601_type

Iso8601_type <|-- Iso8601_time


@enduml