@startuml
' PlantUML diagram for org.openehr.rm.data_types.uri.DV_URI
title DV_URI Class

class DV_URI {
  + value : String [1..1]
  + scheme() : String [0..1]
  + path() : String [0..1]
  + fragment_id() : String [0..1]
  + query() : String [0..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_URI


@enduml