@startuml
' PlantUML diagram for org.openehr.base.bmm.rm_access.BMM_MODEL_ACCESS
title BMM_MODEL_ACCESS Class

class BMM_MODEL_ACCESS {
  + schema_directories : List<String> [0..*]
  + all_schemas : List<String> [0..*]
  + bmm_models : Hash<String,BMM_MODEL> [0..1]
  + matching_bmm_models : List<String> [0..*]
  + initialise_with_load_list(List<String> a_schema_dirs, List<String> a_schema_load_list) : void [0..1]
  + initialise_all(List<String> a_schema_dirs) : void [0..1]
  + reload_schemas() : void [0..1]
  + bmm_model(String a_model_key) : BMM_MODEL [0..1]
  + has_bmm_model(String a_model_key) : Boolean [0..1]
}

class BMM_DEFINITIONS {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ACCESS


@enduml