@startuml

class BMM_MODEL_ACCESS {
  + schema_directories : List<String> [*]
  + all_schemas : List<String> [*]
  + bmm_models : Hash<String,BMM_MODEL> [0..1]
  + matching_bmm_models : List<String> [*]
  + initialise_with_load_list( a_schema_dirs : List<String> [1], a_schema_load_list : List<String> [0..1] ) : void [1]
  + initialise_all( a_schema_dirs : List<String> [1] ) : void [1]
  + reload_schemas() : void [1]
  + bmm_model( a_model_key : String [1] ) : BMM_MODEL [1]
  + has_bmm_model( a_model_key : String [1] ) : Boolean [1]
}

class BMM_DEFINITIONS  #whitesmoke;line:gray;line.dotted;text:gray {
}

BMM_DEFINITIONS <|-- BMM_MODEL_ACCESS


@enduml