@startuml
' PlantUML diagram for org.openehr.base.bmm.rm_access.BMM_SCHEMA_METADATA_KEY
title BMM_SCHEMA_METADATA_KEY Enumeration

enum BMM_SCHEMA_METADATA_KEY {
  bmm_version 
  model_publisher 
  schema_name 
  model_release 
  schema_revision 
  schema_lifecycle_state 
  schema_description 
  schema_path 
}


@enduml