@startuml
' PlantUML diagram for org.openehr.lang.beom.core.EXPR_OPERATOR
title EXPR_OPERATOR Class

abstract class EXPR_OPERATOR {
  + precedence_overridden : Boolean [0..1]
  + operator : OPERATOR_KIND [1..1]
  + symbol : String [0..1]
}

abstract class EXPRESSION {
  + {abstract} type() : EXPR_TYPE_DEF [0..1]
}

abstract class EXPR_VALUE {
  + {abstract} value() : Any [0..1]
}

EXPR_VALUE <|-- EXPRESSION

EXPRESSION <|-- EXPR_OPERATOR


@enduml