@startuml
' PlantUML diagram for org.openehr.lang.beom.core.EXTERNAL_QUERY
title EXTERNAL_QUERY Class

class EXTERNAL_QUERY {
  + context : String [1..1]
  + query_id : String [1..1]
  + query_args : List<String> [0..*]
}

abstract class EXPR_VALUE {
  + {abstract} value() : Any [0..1]
}

EXPR_VALUE <|-- EXTERNAL_QUERY


@enduml