@startuml
' PlantUML diagram for org.openehr.rm.data_types.time_specification.DV_PERIODIC_TIME_SPECIFICATION
title DV_PERIODIC_TIME_SPECIFICATION Class

class DV_PERIODIC_TIME_SPECIFICATION {
  + period() : DV_DURATION [0..1]
  + calendar_alignment() : String [0..1]
  + event_alignment() : String [0..1]
  + institution_specified() : Boolean [0..1]
}

abstract class DV_TIME_SPECIFICATION {
  + value : DV_PARSABLE [1..1]
  + {abstract} calendar_alignment() : String [0..1]
  + {abstract} event_alignment() : String [0..1]
  + {abstract} institution_specified() : Boolean [0..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_TIME_SPECIFICATION

DV_TIME_SPECIFICATION <|-- DV_PERIODIC_TIME_SPECIFICATION


@enduml