@startuml

abstract class Interval <T> {
  + lower : T [0..1]
  + upper : T [0..1]
  + lower_unbounded : Boolean [1]
  + upper_unbounded : Boolean [1]
  + lower_included : Boolean [1]
  + upper_included : Boolean [1]
  + {abstract} has( e : T [1] ) : Boolean [1]
  + {abstract} intersects( other : Interval [1] ) : Boolean [1]
  + {abstract} contains( other : Interval [1] ) : Boolean [1]
  + {abstract} is_equal( other : Any [1] ) : Boolean [1]
}


@enduml