@startuml

abstract class P_C_PRIMITIVE_OBJECT {
  + assumed_value : Any [0..1]
  + is_enumerated_type_constraint : Boolean [0..1]
  + constraint : Any [1]
}

abstract class P_C_DEFINED_OBJECT  #whitesmoke;line:gray;line.dotted;text:gray {
  + is_frozen : Boolean [0..1]
  + default_value : Any [1]
}

abstract class P_C_OBJECT  #whitesmoke;line:gray;line.dotted;text:gray {
  + rm_type_name : String [1]
  + occurrences : String [0..1]
  + node_id : String [1]
  + is_deprecated : Boolean [0..1]
  + specialisation_depth() : Integer [1]
}

abstract class P_ARCHETYPE_CONSTRAINT  #whitesmoke;line:gray;line.dotted;text:gray {
}

P_ARCHETYPE_CONSTRAINT <|-- P_C_OBJECT

P_C_OBJECT <|-- P_C_DEFINED_OBJECT

P_C_DEFINED_OBJECT <|-- P_C_PRIMITIVE_OBJECT


@enduml