@startuml

abstract class BMM_DECLARATION {
  + name : String [1]
  + documentation : Hash<String,Any> [0..1]
  + scope : BMM_DECLARATION [1]
  + extensions : Hash<String,Any> [0..1]
  + is_root_scope() : Boolean [1]
}


@enduml