@startuml

abstract class DV_ENCAPSULATED {
  + charset : CODE_PHRASE [0..1]
  + language : CODE_PHRASE [0..1]
}

class DV_MULTIMEDIA {
  + alternate_text : String [0..1]
  + uri : DV_URI [0..1]
  + data : Array<Octet> [*]
  + media_type : CODE_PHRASE [1]
  + compression_algorithm : CODE_PHRASE [0..1]
  + integrity_check : Array<Octet> [*]
  + integrity_check_algorithm : CODE_PHRASE [0..1]
  + thumbnail : DV_MULTIMEDIA [0..1]
  + size : Integer [1]
  + is_external() : Boolean [1]
  + is_inline() : Boolean [1]
  + is_compressed() : Boolean [1]
  + has_integrity_check() : Boolean [1]
}

class DV_PARSABLE {
  + value : String [1]
  + formalism : String [1]
  + size() : Integer [1]
}

DATA_VALUE <|-- DV_ENCAPSULATED
DV_ENCAPSULATED <|-- DV_MULTIMEDIA
DV_ENCAPSULATED <|-- DV_PARSABLE

@enduml