@startuml

class GENERIC_CONTENT_ITEM {
  + item_type : DV_CODED_TEXT [0..1]
  + item_type_version : String [0..1]
  + author : String [0..1]
  + creation_time : Iso8601_date_time [0..1]
  + authoriser : String [0..1]
  + authorisation_time : Iso8601_date_time [0..1]
  + item_status : DV_CODED_TEXT [0..1]
  + version_id : String [0..1]
  + version_set_id : String [0..1]
  + system_id : String [0..1]
  + other_details : Hash<String,String> [0..1]
  + item : LOCATABLE [0..1]
}

EXTRACT_CONTENT_ITEM <|-- GENERIC_CONTENT_ITEM

@enduml