@startuml

class FUNCTION_DEF_EXAMPLE {
  + identifier : String [1]
  + evaluation_agent : FUNCTION<> [1]
}

abstract class FUNCTION_DEF_EXTERNAL {
  + evaluation_agent : FUNCTION<TUPLE,Any> [1]
}

class OP_DEF_AND {
  + identifier : String [1]
  + symbols : List<String> [*]
  + evaluation_agent : FUNCTION<> [1]
}

class OP_DEF_EXAMPLE {
  + identifier : String [1]
  + symbols : List<String> [*]
  + evaluation_agent : FUNCTION<> [1]
}

class OP_DEF_EXISTS {
  + identifier : String [1]
  + symbols : List<String> [*]
  + evaluation_agent : FUNCTION<> [1]
}

class OP_DEF_PLUS {
  + name : String [1]
  + symbols : List<String> [*]
}

abstract class OPERATOR_DEF_EXTERNAL {
  + evaluation_agent : FUNCTION<TUPLE,Any> [1]
}

FUNCTION_DEF_EXTERNAL <|-- FUNCTION_DEF_EXAMPLE
OPERATOR_DEF_EXTERNAL <|-- OP_DEF_AND
OPERATOR_DEF_EXTERNAL <|-- OP_DEF_EXAMPLE
OPERATOR_DEF_EXTERNAL <|-- OP_DEF_EXISTS

@enduml