@startuml

class EL_BINARY_OPERATOR {
  + left_operand : EL_SIMPLE [1]
  + right_operand : EL_TERMINAL [1]
}

abstract class EL_EXPRESSION {
  + {abstract} eval_type() : BMM_TYPE [1]
  + is_boolean() : Boolean [1]
}

abstract class EL_TERMINAL {
}

class EL_LITERAL {
  + value : BMM_LITERAL_VALUE [1]
  + eval_type() : BMM_TYPE [1]
}

abstract class EL_OPERATOR {
  + precedence_overridden : Boolean [0..1]
  + symbol : String [0..1]
  + definition : BMM_FUNCTION [1]
  + operator_definition() : BMM_OPERATOR [1]
  + equivalent_call() : EL_FUNCTION_CALL [1]
}

class EL_UNARY_OPERATOR {
  + operand : EL_SIMPLE [1]
}

class EL_INSTANTIABLE_REF <T> {
  + definition : T [0..1]
  + eval_type() : BMM_TYPE [1]
}

abstract class EL_PREDICATE {
  + operand : EL_INSTANCE_REF [1]
  + eval_type() : BMM_SIMPLE_TYPE [1]
}

class EL_DEFINED {
}

class EL_FUNCTION_CALL {
  + agent : EL_FUNCTION_AGENT [1]
  + eval_type() : BMM_TYPE [1]
}

abstract class EL_AGENT_CALL {
  + agent : EL_AGENT [1]
}

abstract class EL_AGENT {
  + name : String [1]
  + closed_args : EL_TUPLE [0..1]
  + open_args : List<String> [*]
  + definition : BMM_ROUTINE [0..1]
  + eval_type() : BMM_SIGNATURE [1]
  + is_callable() : Boolean [1]
}

class EL_TUPLE_ITEM {
  + item : EL_EXPRESSION [0..1]
  + name : String [0..1]
}

class EL_PROCEDURE_AGENT {
  + definition : BMM_PROCEDURE [0..1]
}

class EL_TUPLE {
  + items : List<EL_TUPLE_ITEM> [*]
  + type : BMM_TUPLE_TYPE [1]
  + eval_type() : BMM_TYPE [1]
}

class EL_FUNCTION_AGENT {
  + definition : BMM_FUNCTION [0..1]
}

class EL_ATTACHED {
}

abstract class EL_INSTANCE_REF {
}

class EL_SELF_REF {
  + type : BMM_TYPE [1]
  + eval_type() : BMM_TYPE [1]
}

class EL_BOOLEAN_EXPRESSION {
}

class EL_TYPE_REF {
  + type : BMM_TYPE [1]
  + eval_type() : BMM_TYPE [1]
}

abstract class EL_SCOPED_REF {
  + scope : EL_INSTANCE_REF [0..1]
}

class EL_CONDITIONAL_EXPRESSION {
  + condition : EL_SIMPLE [1]
}

class EL_CONDITION_CHAIN {
  + items : List<EL_CONDITIONAL_EXPRESSION> [1..*]
}

abstract class EL_CONSTRAINED {
  + base_expression : EL_EXPRESSION [1]
}

class EL_CASE_TABLE {
  + items : List<EL_CASE> [1..*]
  + input : EL_SIMPLE [1]
}

class EL_CASE {
  + value_constraint : C_OBJECT [1]
}

abstract class EL_DECISION_TABLE {
  + else : EL_EXPRESSION [1]
  + items : List<EL_DECISION_BRANCH> [1..*]
}

abstract class EL_DECISION_BRANCH {
  + result : EL_EXPRESSION [1]
}

abstract class EL_SIMPLE {
}

EL_OPERATOR <|-- EL_BINARY_OPERATOR
EL_SIMPLE <|-- EL_TERMINAL
EL_INSTANCE_REF <|-- EL_LITERAL
EL_SIMPLE <|-- EL_OPERATOR
EL_OPERATOR <|-- EL_UNARY_OPERATOR
EL_SCOPED_REF <|-- EL_INSTANTIABLE_REF
EL_TERMINAL <|-- EL_PREDICATE
EL_PREDICATE <|-- EL_DEFINED
EL_SCOPED_REF <|-- EL_FUNCTION_CALL
EL_AGENT_CALL <|-- EL_FUNCTION_CALL
EL_SCOPED_REF <|-- EL_AGENT
EL_AGENT <|-- EL_PROCEDURE_AGENT
EL_INSTANCE_REF <|-- EL_TUPLE
EL_AGENT <|-- EL_FUNCTION_AGENT
EL_PREDICATE <|-- EL_ATTACHED
EL_TERMINAL <|-- EL_INSTANCE_REF
EL_INSTANCE_REF <|-- EL_SELF_REF
EL_CONSTRAINED <|-- EL_BOOLEAN_EXPRESSION
EL_INSTANCE_REF <|-- EL_TYPE_REF
EL_INSTANCE_REF <|-- EL_SCOPED_REF
EL_DECISION_BRANCH <|-- EL_CONDITIONAL_EXPRESSION
EL_DECISION_TABLE <|-- EL_CONDITION_CHAIN
EL_EXPRESSION <|-- EL_CONSTRAINED
EL_DECISION_TABLE <|-- EL_CASE_TABLE
EL_DECISION_BRANCH <|-- EL_CASE
EL_EXPRESSION <|-- EL_DECISION_TABLE
EL_EXPRESSION <|-- EL_SIMPLE

@enduml