@startuml

class BMM_INTEGER_VALUE {
  + value : Integer [1]
}

class BMM_STRING_VALUE {
  + value : String [1]
}

abstract class BMM_LITERAL_VALUE {
  + value_literal : String [1]
  + value : Any [0..1]
  + syntax : String [0..1]
}

class BMM_BOOLEAN_VALUE {
  + value : Boolean [1]
}

class BMM_PRIMITIVE_VALUE {
  + type : BMM_SIMPLE_TYPE [1]
}

class BMM_CONTAINER_VALUE {
  + type : BMM_CONTAINER_TYPE [1]
}

abstract class BMM_UNITARY_VALUE {
  + type : BMM_UNITARY_TYPE [1]
}

class BMM_INDEXED_CONTAINER_VALUE {
  + type : BMM_INDEXED_CONTAINER_TYPE [1]
}

class BMM_INTERVAL_VALUE {
}

BMM_PRIMITIVE_VALUE <|-- BMM_INTEGER_VALUE
BMM_PRIMITIVE_VALUE <|-- BMM_STRING_VALUE
BMM_TYPED <|-- BMM_LITERAL_VALUE
BMM_PRIMITIVE_VALUE <|-- BMM_BOOLEAN_VALUE
BMM_UNITARY_VALUE <|-- BMM_PRIMITIVE_VALUE
BMM_LITERAL_VALUE <|-- BMM_CONTAINER_VALUE
BMM_LITERAL_VALUE <|-- BMM_UNITARY_VALUE
BMM_CONTAINER_VALUE <|-- BMM_INDEXED_CONTAINER_VALUE
BMM_LITERAL_VALUE <|-- BMM_INTERVAL_VALUE

@enduml