@startuml
' PlantUML diagram for org.openehr.rm.common.generic-PARTY_PROXY
' Generated on 2025-08-08 14:17:14

title PARTY_PROXY class

abstract class PARTY_PROXY {
  + external_ref : PARTY_REF [0..1]
}


@enduml
