@startuml
' PlantUML diagram for org.openehr.rm.data_types.text-DV_PARAGRAPH
title DV_PARAGRAPH class

class DV_PARAGRAPH {
  + items : List<DV_TEXT> [1..*]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_PARAGRAPH


@enduml
