@startuml
' PlantUML diagram for org.openehr.rm.common.generic-PARTY_IDENTIFIED
' Generated on 2025-08-08 14:17:14

title PARTY_IDENTIFIED class

class PARTY_IDENTIFIED {
  + name : String [0..1]
  + identifiers : List<DV_IDENTIFIER> [0..*]
}

abstract class PARTY_PROXY {
  + external_ref : PARTY_REF [0..1]
}

PARTY_PROXY <|-- PARTY_IDENTIFIED


@enduml
