@startuml
' PlantUML diagram for org.openehr.rm.support.terminology-OPENEHR_CODE_SET_IDENTIFIERS
' Generated on 2025-08-08 14:17:14

title OPENEHR_CODE_SET_IDENTIFIERS class

class OPENEHR_CODE_SET_IDENTIFIERS {
  + valid_code_set_id(String an_id) : Boolean [0..1]
}


@enduml
