@startuml
' PlantUML diagram for org.openehr.rm.data_types.basic-DV_STATE
title DV_STATE class

class DV_STATE {
  + value : DV_CODED_TEXT [1..1]
  + is_terminal : Boolean [1..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_STATE


@enduml
