@startuml
' PlantUML diagram for org.openehr.base.base_types.identification-INTERNET_ID
title INTERNET_ID class

class INTERNET_ID {
}

abstract class UID {
  + value : String [1..1]
}

UID <|-- INTERNET_ID


@enduml
