@startuml
' PlantUML diagram for org.openehr.rm.common.change_control-ORIGINAL_VERSION
' Generated on 2025-08-08 14:17:14

title ORIGINAL_VERSION class

class ORIGINAL_VERSION <<T>> {
  + uid : OBJECT_VERSION_ID [1..1]
  + preceding_version_uid : OBJECT_VERSION_ID [0..1]
  + other_input_version_uids : List<OBJECT_VERSION_ID> [0..*]
  + lifecycle_state : DV_CODED_TEXT [1..1]
  + attestations : List<ATTESTATION> [0..*]
  + data : T [0..1]
  + is_merged() : Boolean [0..1]
}

abstract class VERSION <<T>> {
  + contribution : OBJECT_REF [1..1]
  + signature : String [0..1]
  + commit_audit : AUDIT_DETAILS [1..1]
  + {abstract} uid() : OBJECT_VERSION_ID [0..1]
  + {abstract} preceding_version_uid() : OBJECT_VERSION_ID [0..1]
  + {abstract} data() : T [0..1]
  + {abstract} lifecycle_state() : DV_CODED_TEXT [0..1]
  + canonical_form() : String [0..1]
  + owner_id() : HIER_OBJECT_ID [0..1]
  + is_branch() : Boolean [0..1]
}

VERSION <|-- ORIGINAL_VERSION


@enduml
