@startuml
' PlantUML diagram for org.openehr.base.foundation_types.structure-List
' Generated on 2025-08-08 14:17:14

title List class

class List <<T>> {
  + first() : T [0..1]
  + last() : T [0..1]
}

abstract class Container <<T>> {
  + {abstract} has(T v) : Boolean [0..1]
  + {abstract} count() : Integer [0..1]
  + {abstract} is_empty() : Boolean [0..1]
  + there_exists(Operation test) : Boolean [0..1]
  + for_all(Operation test) : Boolean [0..1]
  + matching(Operation test) : List<T> [1..*]
  + select(Operation test) : T [1..1]
}

Container <|-- List


@enduml
