@startuml
' PlantUML diagram for org.openehr.rm.resource-CONSUMABLE_USE
title CONSUMABLE_USE class

class CONSUMABLE_USE {
  + amount : DATA_VALUE [0..1]
}

abstract class RESOURCE_USE {
  + cost_data : ITEM_STRUCTURE [0..1]
}

RESOURCE_USE <|-- CONSUMABLE_USE


@enduml
