@startuml
' PlantUML diagram for org.openehr.rm.data_types.encapsulated-DV_ENCAPSULATED
' Generated on 2025-08-08 14:17:14

title DV_ENCAPSULATED class

abstract class DV_ENCAPSULATED {
  + charset : CODE_PHRASE [0..1]
  + language : CODE_PHRASE [0..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_ENCAPSULATED


@enduml
