@startuml
' PlantUML diagram for org.openehr.rm.common.archetyped-PATHABLE
' Generated on 2025-08-08 14:17:14

title PATHABLE class

abstract class PATHABLE {
  + parent() : PATHABLE [0..1]
  + item_at_path(String a_path) : Any [0..1]
  + items_at_path(String a_path) : List<Any> [1..*]
  + path_exists(String a_path) : Boolean [0..1]
  + path_unique(String a_path) : Boolean [0..1]
  + path_of_item(PATHABLE a_loc) : String [0..1]
}


@enduml
