@startuml
' PlantUML diagram for org.openehr.rm.data_types.text-TERM_MAPPING
' Generated on 2025-08-08 14:17:14

title TERM_MAPPING class

class TERM_MAPPING {
  + match : Character [1..1]
  + purpose : DV_CODED_TEXT [0..1]
  + target : CODE_PHRASE [1..1]
  + narrower() : Boolean [0..1]
  + broader() : Boolean [0..1]
  + equivalent() : Boolean [0..1]
  + unknown() : Boolean [0..1]
  + is_valid_match_code(Character c) : Boolean [0..1]
}


@enduml
