@startuml
' PlantUML diagram for org.openehr.rm.data_structures.item_structure-ITEM_TABLE
' Generated on 2025-08-08 14:17:14

title ITEM_TABLE class

class ITEM_TABLE {
  + rows : List<CLUSTER> [0..*]
  + row_count() : Integer [0..1]
  + column_count() : Integer [0..1]
  + row_names() : List<DV_TEXT> [1..*]
  + column_names() : List<DV_TEXT> [1..*]
  + ith_row(Integer i) : CLUSTER [0..1]
  + has_row_with_name(String a_key) : Boolean [0..1]
  + has_column_with_name(String a_key) : Boolean [0..1]
  + named_row(String a_key) : CLUSTER [0..1]
  + has_row_with_key(List<String> keys) : Boolean [0..1]
  + row_with_key(List<String> keys) : CLUSTER [0..1]
  + element_at_cell_ij(Integer i, Integer j) : ELEMENT [0..1]
  + as_hierarchy() : CLUSTER [0..1]
}

abstract class ITEM_STRUCTURE {
}

abstract class DATA_STRUCTURE {
  + as_hierarchy() : ITEM [0..1]
}

abstract class LOCATABLE {
  + name : DV_TEXT [1..1]
  + archetype_node_id : String [1..1]
  + uid : UID_BASED_ID [0..1]
  + links : List<LINK> [0..*]
  + archetype_details : ARCHETYPED [0..1]
  + feeder_audit : FEEDER_AUDIT [0..1]
  + concept() : DV_TEXT [0..1]
  + is_archetype_root() : Boolean [0..1]
}

abstract class PATHABLE {
  + parent() : PATHABLE [0..1]
  + item_at_path(String a_path) : Any [0..1]
  + items_at_path(String a_path) : List<Any> [1..*]
  + path_exists(String a_path) : Boolean [0..1]
  + path_unique(String a_path) : Boolean [0..1]
  + path_of_item(PATHABLE a_loc) : String [0..1]
}

PATHABLE <|-- LOCATABLE

LOCATABLE <|-- DATA_STRUCTURE

DATA_STRUCTURE <|-- ITEM_STRUCTURE

ITEM_STRUCTURE <|-- ITEM_TABLE


@enduml
