@startuml
' PlantUML diagram for org.openehr.rm.data_types.quantity-DV_INTERVAL
title DV_INTERVAL class

class DV_INTERVAL <<T>> {
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_INTERVAL

Interval <|-- DV_INTERVAL


@enduml
