@startuml
' PlantUML diagram for org.openehr.base.base_types.definitions-VERSION_STATUS
title VERSION_STATUS class

enum VERSION_STATUS {
  alpha 
  beta 
  release_candidate 
  released 
  build 
}


@enduml
