@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types-Double
' Generated on 2025-08-08 14:17:14

title Double class

class Double {
  + floor() : Integer [0..1]
  + add(Double other) : Double [0..1]
  + subtract(Double other) : Double [0..1]
  + multiply(Double other) : Double [0..1]
  + divide(Double other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + less_than(Double other) : Boolean [0..1]
  + negative() : Double [0..1]
  + is_equal(Double other) : Boolean [0..1]
  + equal(Double other) : Boolean [0..1]
}

abstract class Ordered_Numeric {
}

abstract class Ordered {
  + {abstract} less_than(Ordered other) : Boolean [0..1]
  + less_than_or_equal(Ordered other) : Boolean [0..1]
  + greater_than(Ordered other) : Boolean [0..1]
  + greater_than_or_equal(Ordered other) : Boolean [0..1]
}

Ordered <|-- Ordered_Numeric

abstract class Numeric {
  + {abstract} add(Numeric other) : Numeric [0..1]
  + {abstract} subtract(Numeric other) : Numeric [0..1]
  + {abstract} multiply(Numeric other) : Numeric [0..1]
  + {abstract} divide(Numeric other) : Numeric [0..1]
  + {abstract} exponent(Numeric other) : Numeric [0..1]
  + {abstract} negative() : Numeric [0..1]
}

Numeric <|-- Ordered_Numeric

Ordered_Numeric <|-- Double


@enduml
