@startuml
' PlantUML diagram for org.openehr.base.foundation_types.structure-Container
title Container class

abstract class Container <<T>> {
  + {abstract} has(T v) : Boolean [0..1]
  + {abstract} count() : Integer [0..1]
  + {abstract} is_empty() : Boolean [0..1]
  + there_exists(Operation test) : Boolean [0..1]
  + for_all(Operation test) : Boolean [0..1]
  + matching(Operation test) : List<T> [1..*]
  + select(Operation test) : T [1..1]
}


@enduml
