@startuml
' PlantUML diagram for org.openehr.base.base_types.identification-OBJECT_ID
' Generated on 2025-08-08 14:17:14

title OBJECT_ID class

abstract class OBJECT_ID {
  + value : String [1..1]
}


@enduml
