@startuml
' PlantUML diagram for org.openehr.base.base_types.identification-ISO_OID
' Generated on 2025-08-08 14:17:14

title ISO_OID class

class ISO_OID {
}

abstract class UID {
  + value : String [1..1]
}

UID <|-- ISO_OID


@enduml
