@startuml
' PlantUML diagram for org.openehr.rm.data_types.encapsulated-DV_PARSABLE
title DV_PARSABLE class

class DV_PARSABLE {
  + value : String [1..1]
  + formalism : String [1..1]
  + size() : Integer [0..1]
}

abstract class DV_ENCAPSULATED {
  + charset : CODE_PHRASE [0..1]
  + language : CODE_PHRASE [0..1]
}

abstract class DATA_VALUE {
}

DATA_VALUE <|-- DV_ENCAPSULATED

DV_ENCAPSULATED <|-- DV_PARSABLE


@enduml
