@startuml
' PlantUML diagram for org.openehr.base.base_types.identification-GENERIC_ID
title GENERIC_ID class

class GENERIC_ID {
  + scheme : String [1..1]
}

abstract class OBJECT_ID {
  + value : String [1..1]
}

OBJECT_ID <|-- GENERIC_ID


@enduml
