@startuml
' PlantUML diagram for org.openehr.base.base_types.definitions-OPENEHR_DEFINITIONS
title OPENEHR_DEFINITIONS class

class OPENEHR_DEFINITIONS {
}

class BASIC_DEFINITIONS {
}

BASIC_DEFINITIONS <|-- OPENEHR_DEFINITIONS


@enduml
