@startuml
' PlantUML diagram for org.openehr.rm.composition-EVENT_CONTEXT
' Generated on 2025-08-08 14:17:14

title EVENT_CONTEXT class

class EVENT_CONTEXT {
  + start_time : DV_DATE_TIME [1..1]
  + end_time : DV_DATE_TIME [0..1]
  + location : String [0..1]
  + setting : DV_CODED_TEXT [1..1]
  + other_context : ITEM_STRUCTURE [0..1]
  + health_care_facility : PARTY_IDENTIFIED [0..1]
  + participations : List<PARTICIPATION> [0..*]
}

abstract class PATHABLE {
  + parent() : PATHABLE [0..1]
  + item_at_path(String a_path) : Any [0..1]
  + items_at_path(String a_path) : List<Any> [1..*]
  + path_exists(String a_path) : Boolean [0..1]
  + path_unique(String a_path) : Boolean [0..1]
  + path_of_item(PATHABLE a_loc) : String [0..1]
}

PATHABLE <|-- EVENT_CONTEXT


@enduml
