@startuml
' PlantUML diagram for org.openehr.rm.common.resource-TRANSLATION_DETAILS
' Generated on 2025-08-08 14:17:14

title TRANSLATION_DETAILS class

class TRANSLATION_DETAILS {
  + language : CODE_PHRASE [1..1]
  + author : Hash<String,String> [1..1]
  + accreditaton : String [0..1]
  + other_details : Hash<String,String> [0..1]
}


@enduml
