@startuml
' PlantUML diagram for org.openehr.rm.data_types.uri
' Generated on 2025-08-08 14:17:14

title org.openehr.rm.data_types.uri package

class DV_URI {
  + value : String [1..1]
  + scheme() : String [0..1]
  + path() : String [0..1]
  + fragment_id() : String [0..1]
  + query() : String [0..1]
}

class DV_EHR_URI {
}

DATA_VALUE <|-- DV_URI
DV_URI <|-- DV_EHR_URI

@enduml
