@startuml
' PlantUML diagram for org.openehr.rm.support.measurement
' Generated on 2025-08-08 14:17:14

title org.openehr.rm.support.measurement package

class MEASUREMENT_SERVICE {
  + is_valid_units_string(String units) : Boolean [0..1]
  + units_equivalent(String units1, String units2) : Boolean [0..1]
}


@enduml
