@startuml
' PlantUML diagram for org.openehr.base.foundation_types.primitive_types
' Generated on 2025-08-08 14:17:14

title org.openehr.base.foundation_types.primitive_types package

class Uri {
}

abstract class Comparable {
}

abstract class Ordered_Numeric {
}

class Integer {
  + add(Integer other) : Integer [0..1]
  + subtract(Integer other) : Integer [0..1]
  + multiply(Integer other) : Integer [0..1]
  + divide(Integer other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + modulo(Integer mod) : Integer [0..1]
  + less_than(Integer other) : Boolean [0..1]
  + negative() : Integer [0..1]
  + is_equal(Integer other) : Boolean [0..1]
  + equal(Integer other) : Boolean [0..1]
}

class Double {
  + floor() : Integer [0..1]
  + add(Double other) : Double [0..1]
  + subtract(Double other) : Double [0..1]
  + multiply(Double other) : Double [0..1]
  + divide(Double other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + less_than(Double other) : Boolean [0..1]
  + negative() : Double [0..1]
  + is_equal(Double other) : Boolean [0..1]
  + equal(Double other) : Boolean [0..1]
}

abstract class Numeric {
  + {abstract} add(Numeric other) : Numeric [0..1]
  + {abstract} subtract(Numeric other) : Numeric [0..1]
  + {abstract} multiply(Numeric other) : Numeric [0..1]
  + {abstract} divide(Numeric other) : Numeric [0..1]
  + {abstract} exponent(Numeric other) : Numeric [0..1]
  + {abstract} negative() : Numeric [0..1]
}

class Octet {
}

class Character {
}

class Boolean {
  + conjunction(Boolean other) : Boolean [0..1]
  + semistrict_conjunction(Boolean other) : Boolean [0..1]
  + disjunction(Boolean other) : Boolean [0..1]
  + semistrict_disjunction(Boolean other) : Boolean [0..1]
  + exclusive_disjunction(Boolean other) : Boolean [0..1]
  + implication(Boolean other) : Boolean [0..1]
  + negation() : Boolean [0..1]
}

class String {
  + is_empty() : Boolean [0..1]
  + is_integer() : Boolean [0..1]
  + as_integer() : Integer [0..1]
  + append(String other) : String [0..1]
  + less_than(String other) : Boolean [0..1]
  + contains(String other) : Boolean [0..1]
}

class Real {
  + floor() : Integer [0..1]
  + add(Real other) : Real [0..1]
  + subtract(Real other) : Real [0..1]
  + multiply(Real other) : Real [0..1]
  + divide(Real other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + less_than(Real other) : Boolean [0..1]
  + negative() : Real [0..1]
  + is_equal(Real other) : Boolean [0..1]
  + equal(Real other) : Boolean [0..1]
}

class Integer64 {
  + add(Integer other) : Integer64 [0..1]
  + subtract(Integer other) : Integer64 [0..1]
  + multiply(Integer other) : Integer64 [0..1]
  + divide(Integer other) : Double [0..1]
  + exponent(Double other) : Double [0..1]
  + modulo(Integer mod) : Integer64 [0..1]
  + less_than(Integer64 other) : Boolean [0..1]
  + negative() : Integer64 [0..1]
  + is_equal(Integer64 other) : Boolean [0..1]
  + equal(Integer64 other) : Boolean [0..1]
}

abstract class Ordered {
  + {abstract} less_than(Ordered other) : Boolean [0..1]
  + less_than_or_equal(Ordered other) : Boolean [0..1]
  + greater_than(Ordered other) : Boolean [0..1]
  + greater_than_or_equal(Ordered other) : Boolean [0..1]
}

String <|-- Uri
Ordered <|-- Ordered_Numeric
Numeric <|-- Ordered_Numeric
Ordered_Numeric <|-- Integer
Ordered_Numeric <|-- Double
Ordered <|-- Octet
Ordered <|-- Character
Ordered <|-- String
Ordered_Numeric <|-- Real
Ordered_Numeric <|-- Integer64

@enduml
