@startuml
' PlantUML diagram for org.openehr.base.foundation_types.interval
' Generated on 2025-08-08 11:19:48

title org.openehr.base.foundation_types.interval package

class Multiplicity_interval {
}

class Proper_interval {
}

abstract class Interval {
  + lower : T
  + upper : T
  + lower_unbounded : Boolean
  + upper_unbounded : Boolean
  + lower_included : Boolean
  + upper_included : Boolean
}

class Point_interval {
  + lower_unbounded : Boolean
  + upper_unbounded : Boolean
  + lower_included : Boolean
  + upper_included : Boolean
}

class Cardinality {
  + interval : Multiplicity_interval
  + is_ordered : Boolean
  + is_unique : Boolean
}

Proper_interval <|-- Multiplicity_interval
Interval <|-- Proper_interval
Interval <|-- Point_interval

@enduml
