@startuml
' PlantUML diagram for org.openehr.base.foundation_types.structure
' Generated on 2025-08-08 11:19:48

title org.openehr.base.foundation_types.structure package

class Hash {
}

abstract class Container {
}

class List {
}

class Set {
}

class Array {
}

Container <|-- Hash
Container <|-- List
Container <|-- Set
Container <|-- Array

@enduml
