@startuml
' PlantUML diagram for org.openehr.base.foundation_types.terminology
' Generated on 2025-08-08 14:17:14

title org.openehr.base.foundation_types.terminology package

class Terminology_code {
  + terminology_id : String [1..1]
  + terminology_version : String [0..1]
  + code_string : String [1..1]
  + uri : Uri [0..1]
}

class Terminology_term {
  + concept : Terminology_code [1..1]
  + text : String [1..1]
}


@enduml
