@startuml
' PlantUML diagram for org.openehr.base.base_types.identification
' Generated on 2025-08-08 11:19:48

title org.openehr.base.base_types.identification package

class ARCHETYPE_ID {
}

class GENERIC_ID {
  + scheme : String
}

class HIER_OBJECT_ID {
}

class LOCATABLE_REF {
  + path : String
  + id : UID_BASED_ID
}

abstract class OBJECT_ID {
  + value : String
}

class OBJECT_REF {
  + namespace : String
  + type : String
  + id : OBJECT_ID
}

class OBJECT_VERSION_ID {
}

class PARTY_REF {
}

class TERMINOLOGY_ID {
}

class VERSION_TREE_ID {
  + value : String
}

abstract class UID_BASED_ID {
}

class UUID {
}

class INTERNET_ID {
}

abstract class UID {
  + value : String
}

class ISO_OID {
}

class TEMPLATE_ID {
}

class ACCESS_GROUP_REF {
}

OBJECT_ID <|-- ARCHETYPE_ID
OBJECT_ID <|-- GENERIC_ID
UID_BASED_ID <|-- HIER_OBJECT_ID
OBJECT_REF <|-- LOCATABLE_REF
UID_BASED_ID <|-- OBJECT_VERSION_ID
OBJECT_REF <|-- PARTY_REF
OBJECT_ID <|-- TERMINOLOGY_ID
OBJECT_ID <|-- UID_BASED_ID
UID <|-- UUID
UID <|-- INTERNET_ID
UID <|-- ISO_OID
OBJECT_ID <|-- TEMPLATE_ID
OBJECT_REF <|-- ACCESS_GROUP_REF

@enduml
