@startuml
' PlantUML diagram for org.openehr.rm.integration
' Generated on 2025-08-08 14:17:14

title org.openehr.rm.integration package

class GENERIC_ENTRY {
  + data : ITEM_TREE [1..1]
}

CONTENT_ITEM <|-- GENERIC_ENTRY

@enduml
