@startuml

class Array <T> {
}

abstract class Aggregate <T>  #whitesmoke;line:gray;line.dotted;text:gray {
  + {abstract} has( v : T [1] ) : Boolean [1]
  + {abstract} count() : Integer [1]
  + {abstract} is_empty() : Boolean [1]
}

Aggregate <|-- Array


@enduml