@startuml
' PlantUML diagram for org.openehr.rm.ehr_extract.message
title message Package

class MESSAGE {
  + audit : AUDIT_DETAILS [1..1]
  + author : PARTY_PROXY [1..1]
  + content : MESSAGE_CONTENT [1..1]
  + signature : String [0..1]
}

class ADDRESSED_MESSAGE {
  + sender : String [1..1]
  + sender_reference : String [1..1]
  + addressees : List<String> [1..*]
  + urgency : Integer [0..1]
  + message : MESSAGE [1..1]
}

abstract class MESSAGE_CONTENT {
}


@enduml